### PR TITLE
Template the project Ballerina.toml file

### LINKED ISSUE #1007: Template the Ballerina.toml file inside the microgateway project
### Description:
Since the Ballerina.toml file created inside the project target directory getting edited due to pilicy hub dependency addition as well as java interceptor platform libraries, we need to template the Ballerina.toml file
### Environment details (with versions):
- OS:
- Client:
- Env (Docker/K8s):

---

### LINKED ISSUE #1101: Interceptor module version is ignored during the build
### Description:

When importing a module from [policy hub](central.ballerina.io), module version provided in openapi extension is ignored.
### Steps to reproduce:
1. Add a versioned interceptor module to an openapi file (Ex: `x-wso2-response-interceptor: "praminda/formatters/0.2.0:formatResponse"`)
1. Build the micro-gw project.
1. Inspect the build log and check the version pulled from the policy hub.
   ```
   Compiling source
	   wso2/petstore:3.1.0
	   praminda/formatters:0.3.0 [central.ballerina.io -> home repo]
   ```
1. Latest version of the module is pulled, not the specified version.
### Affected Product Version:

3.1.0-beta
### Environment details (with versions):
- OS: MacOS
- Client:
- Env (Docker/K8s):

### PR DESCRIPTION
**Pull request by praminda**
### Purpose

Templating the `Ballerina.toml` of microgateway project. This will avoid confusions when trying to add/update elements such as dependencies and libs into this file programmatically. 
### Issues

Fixes #1007 
Fixes #1101 
### Automation tests
 - Unit tests added: No
 - Integration tests added: No

### Tested environments

MacOs

---
#### Maintainers: Check before merge
- [x] Assigned 'Type' label
- [x] Assigned the project
- [x] Validated respective github issues
- [x] Assigned milestone to the github issue(s)

### CODE REVIEW

File: components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/model/template/BallerinaLibrary.java [hunk 1]
```diff
@@ -0,0 +1,70 @@
...
+        this.version = version;
+    }
+
+    public String getGroupId() {
+        return groupId;
+    }
+
+    public void setGroupId(String groupId) {
+        this.groupId = groupId;
+    }
```
Comment (Rajith90) [inline components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/model/template/BallerinaLibrary.java]: lets remove the above gette and setters

Comment (praminda) [reply components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/model/template/BallerinaLibrary.java]: Why? we need those to set and get these values from `BallerinaToml`

Comment (Rajith90) [reply components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/model/template/BallerinaLibrary.java]: We don't need those values in ballerina.toml. So we can remove them, otherwise those values can give the idea that it can download the maven dependencies
