### PR TITLE
Bug fix: [Enforcer] Fix the issue where path parameters does not resolve depending on the trailing slash

### LINKED ISSUE #2439: PathParameters does not resolve if the rawPath contains a trailing slash
### Description:
If there is a path called `/pet/{petId}` and the inbound request has `/pet/2/`. Due to trailing slash, the path parameters are not resolved for the usage of custom filters.

And following error log also getting printed.
```
PathTemplate and RawPath is mismatched.
```

### Steps to reproduce:
Refer to the description.

### Affected Product Version:
Choreo-Connect-1.0.0-alpha

### Environment details (with versions):
- OS:
- Client:
- Env (Docker/K8s):

---

### PR DESCRIPTION
**Pull request by VirajSalaka**
### Purpose
$subject. 

In addition, allow path parameters to contain hyphen and underscore.

### Issues

Fixes #2439 

### Automation tests
 - Unit tests added: Yes
 - Integration tests added: No

### Tested environments

Not Tested

---
#### Maintainers: Check before merge
- [x] Assigned 'Type' label
- [x] Assigned the project
- [x] Validated respective github issues
- [x] Assigned milestone to the github issue(s)

### CODE REVIEW

**Review by praminda — APPROVED** [review]

**Review by pubudu538 — APPROVED** [review]

File: enforcer-parent/commons/src/main/java/org/wso2/choreo/connect/enforcer/commons/model/ParameterResolver.java [hunk 1]
```diff
@@ -29,14 +29,16 @@
 
 class ParameterResolver {
 
-    private static final Pattern PARAMETER_PATTERN = Pattern.compile("(\\{[a-zA-Z]+\\})");
+    private static final Pattern PARAMETER_PATTERN = Pattern.compile("(\\{[a-zA-Z0-9]+[a-z-_A-Z0-9]*\\})");
```
Comment (renuka-fernando) [inline enforcer-parent/commons/src/main/java/org/wso2/choreo/connect/enforcer/commons/model/ParameterResolver.java:32]: can parameter end with "-" ?

Comment (VirajSalaka) [reply enforcer-parent/commons/src/main/java/org/wso2/choreo/connect/enforcer/commons/model/ParameterResolver.java:32]: In the  openapi specification there is no clear mention, but in the API Manager we could assign such variables as well.

**Review by renuka-fernando — APPROVED** [review]

**Comment by choreo-cicd** [comment]
[succeeded] dev-deployment : 20211202.25
