### PR TITLE
Fix #1148 #1149 - API level throttling issues in distributed setup

### LINKED ISSUE #1113: Provide a way to template the base path extension of open API
### Describe your problem(s)
Currently the x-wso2-basePath extension value is directly used as the context to expose the API. 
There should be way to append/prepend or include open API version also into the base path in which the API is exposed

### Describe your solution
Introduce a new extension called **x-wso2-context-template** in order to template the base path of the API

### How will you implement it

---

### LINKED ISSUE #1141: Basic authentication does not support other hashing algorithms (apart from SHA1)
### Description:
When a user is added from the micro-gw.conf file, the password can only be in SHA1 though the template configuration file states that it can be in other hashing algorithms as well with a prefix.

### Steps to reproduce:
1. Create and build a project with an endpoint with basic auth
2. Add a user to micro-gw.conf file with a different hashing algorithm.
`[b7a.users.johndoe]`
`password = "@sha256:{5e884898da28047151d0e56f8dc6292773603d0d6aabbdd62a11ef721d1542d8}"`
3. curl a request with basic auth

### Affected Product Version:
3.1.0

### LINKED ISSUE #1148: Distributed Throttling is not working.
### Description:
When distributed throttling is enabled, the requests do not thottle out.
In the Traffic Manager, we can see the following log.
```
[2020-03-18 13:07:03,530] ERROR - FunctionExecutor Exception on execution plan 'requestPreProcessorExecutionPlan' on class 'org.wso2.siddhi.extension.map.CreateFromJSONFunctionExtension', Cannot create JSON from '' in create from json function
org.wso2.siddhi.core.exception.ExecutionPlanRuntimeException: Cannot create JSON from '' in create from json function
at org.wso2.siddhi.extension.map.CreateFromJSONFunctionExtension.execute(CreateFromJSONFunctionExtension.java:65) ~[siddhi-extension-map_3.2.6.jar:?]
at org.wso2.siddhi.core.executor.function.FunctionExecutor.execute(FunctionExecutor.java:94) [siddhi-core_3.2.6.jar:?]
at org.wso2.siddhi.core.executor.function.FunctionExecutor.execute(FunctionExecutor.java:98) [siddhi-core_3.2.6.jar:?]
at org.wso2.siddhi.core.query.selector.attribute.processor.AttributeProcessor.process(AttributeProcessor.java:38) [siddhi-core_3.2.6.jar:?]
at org.wso2.siddhi.core.query.selector.QuerySelector.processNoGroupBy(QuerySelector.java:103) [siddhi-core_3.2.6.jar:?]
at org.wso2.siddhi.core.query.selector.QuerySelector.process(QuerySelector.java:86) [siddhi-core_3.2.6.jar:?]
at org.wso2.siddhi.core.query.input.ProcessStreamReceiver.processAndClear(ProcessStreamReceiver.java:178) [siddhi-core_3.2.6.jar:?]
at org.wso2.siddhi.core.query.input.ProcessStreamReceiver.process(ProcessStreamReceiver.java:88) [siddhi-core_3.2.6.jar:?]
at org.wso2.siddhi.core.query.input.ProcessStreamReceiver.receive(ProcessStreamReceiver.java:174) [siddhi-core_3.2.6.jar:?]
at org.wso2.siddhi.core.stream.StreamJunction.sendData(StreamJunction.java:219) [siddhi-core_3.2.6.jar:?]
at org.wso2.siddhi.core.stream.StreamJunction.access$200(StreamJunction.java:47) [siddhi-core_3.2.6.jar:?]
at org.wso2.siddhi.core.stream.StreamJunction$Publisher.send(StreamJunction.java:348) [siddhi-core_3.2.6.jar:?]
at org.wso2.siddhi.core.stream.input.InputDistributor.send(InputDistributor.java:49) [siddhi-core_3.2.6.jar:?]
```
The reason behind this was that the event contains an empty field called properties. But the Traffic Manager expects it to be a json. So the solution would be setting that property to an empty json.

### Steps to reproduce:
Enable distributed throttling and invoke the gateway.

### Affected Product Version:
3.1.0-beta

### Environment details (with versions):
- OS: MacOS Mojave
- Client:
- Env (Docker/K8s):
- API Manager - 3.1.0-rc1

---
#### Suggested Labels:
Affected/3.1.0-beta

### LINKED ISSUE #1149: Distributed Throttling with API level tier does not work
### Description:
When distributed throttling is enabled and the API only has a API-level throttling tier, the requests do not throttle out at all.

When microgateway debug logs are enabled, we can see the following log message.
```
2020-03-18 17:11:58,729 DEBUG [wso2/gateway/src/gateway/utils] - [ThrottleFilter] [4abba77c-e25e-42f5-91fe-681703995664] Resource key : get701be7b43c654cea81c1ac4003b6885b:1.0.0
Subscription key : 1:/pizzashack/1.0.0:1.0.0
App key : 1:admin@carbon.super
API key : /pizzashack/1.0.0:1.0.0
Resource Tier : Unlimited
Subscription Tier : Unlimited
App Tier : Unlimited
API Tier : 10KPerMin 
```
And the event which is sent by the microgateway looks like this.
`{"event":{"metaData":{}, "correlationData":{}, "payloadData":{"messageID":"4abba77c-e25e-42f5-91fe-681703995664", "appKey":"1:admin@carbon.super", "appTier":"Unlimited", "apiKey":"/pizzashack/1.0.0:1.0.0", "apiTier":"10KPerMin", "subscriptionKey":"1:/pizzashack/1.0.0:1.0.0", "subscriptionTier":"Unlimited", "resourceKey":"get701be7b43c654cea81c1ac4003b6885b:1.0.0", "resourceTier":"Unlimited", "userId":"admin@carbon.super", "apiContext":"/pizzashack/1.0.0", "apiVersion":"1.0.0", "appTenant":"carbon.super", "apiTenant":"carbon.super", "appId":"1", "apiName":"PizzaShackAPI__1_0_0", "properties":{}}}}`

There is no event received from the Traffic Manager even though the quota is exceeded.

### Steps to reproduce:
Add API level throttle policy to the openAPI definition. Make sure the same policy is created in the API Manager node. Start the gateway with distributed throttling enabled.

### Affected Product Version:
Current Master branch

### Environment details (with versions):
- OS: MacOS Mojave
- Client:
- Env (Docker/K8s):
- API Manager: 3.1.0-rc1

---
#### Suggested Labels:
Affected/3.1.0-beta

### PR DESCRIPTION
**Pull request by Rajith90**
### Purpose
This fixes issue with distributed throttling and API level throttling when used with distributed setup.

### Issues

Fixes #1148 
Fixes #1149 
Fixes #1141 
Fixes #1113 

### Automation tests
 - Unit tests added: Yes/No
 - Integration tests added: Yes/No

### Tested environments

Not Tested

---
#### Maintainers: Check before merge
- [x] Assigned 'Type' label
- [x] Assigned the project
- [x] Validated respective github issues
- [x] Assigned milestone to the github issue(s)

### CODE REVIEW

File: components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/cmd/BuildCmd.java [hunk 1]
```diff
@@ -129,7 +129,7 @@ public void execute() {
             }
             String toolkitConfigPath = CmdUtils.getMainConfigLocation();
             init(projectName, toolkitConfigPath, deploymentConfigPath);
-            outStream.print("Generating sources...");
+            outStream.print("Generating sources... \n");
```
Comment (praminda) [inline components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/cmd/BuildCmd.java]: This doesn't look good. This makes the `[DONE]` printed in next line which is not professional at all IMO. Earlier we had few difficulties in printing this in one line but I fixed it recently in one of my PRs. If we need to print warn messages then the best option is to keep all messages in a list and print those after the build command execution, in the `Main.java`

File: tests/src/test/resources/openAPIs/throttling/throttle.yaml [hunk 2]
```diff
@@ -0,0 +1,104 @@
...
+              schema:
+                $ref: "#/components/schemas/Pet"
+        "400":
+          description: Invalid ID supplied
+        "404":
+          description: Pet not found
+      security:
+        - api_key: []
+          api_key_query: []
+        - petstore_auth: []
```
Comment (praminda) [inline tests/src/test/resources/openAPIs/throttling/throttle.yaml]:
```suggestion
        - petstore_auth: []

```

File: components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/cmd/BuildCmd.java (hunk 1 above)
Comment (praminda) [reply components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/cmd/BuildCmd.java]: If any of the options doesn't work my opinion is we should remove the half baked`Generating sources` message completely from the build output.
