### PR TITLE
Bug fixes: Improve subscription validation flow [Don't Merge]

### LINKED ISSUE #1712: Improve Subscription Validation flow
### Describe your problem(s)
Currently, when the API created event is received by the microgateway, it calls `internal/data/v1/apis` endpoint to populate the API object required for subscription validation. But this REST endpoint call can be avoided because the APIID field is included within later APIM versions. (APIM m8 onwards).

[edited]
With API Manager 4.0.0, subscription UUID is introduced and it contains API and APP UUIDs. Hence we could use UUIDs for subscription validation.

### How will you implement it

---

### PR DESCRIPTION
**Pull request by VirajSalaka**
### Purpose

$subject

### Issues

Fixes #1712 

### Automation tests
 - Unit tests added: No
 - Integration tests added: No (Covered by already available tests)

### Tested environments

Not Tested

---
#### Maintainers: Check before merge
- [x] Assigned 'Type' label
- [x] Assigned the project
- [x] Validated respective github issues
- [x] Assigned milestone to the github issue(s)

### CODE REVIEW

File: adapter/internal/messaging/notification_listener.go [hunk 1]
```diff
@@ -138,15 +138,36 @@ func handleAPIEvents(data []byte, eventType string) {
...
+						var apiEvent APIEvent
+						json.Unmarshal([]byte(string(data)), &apiEvent)
+						api := types.API{
+							APIID:    apiEvent.APIID,
+							UUID:     apiEvent.UUID,
+							Provider: apiEvent.APIProvider,
+							// hardcoded as default version is not assigned at the moment.
+							IsDefaultVersion: false,
+							APIStatus:        apiEvent.APIStatus,
+							TenantID:         apiEvent.TenantID,
```
Comment (VirajSalaka) [inline adapter/internal/messaging/notification_listener.go:150]: blocking condition's event vs deployevent 's lifecycle status needs to be checked.

**Review by Rajith90 — APPROVED** [review]
