### PR TITLE
Fixes for schema validation feature

### LINKED ISSUE #936: How to specify that additional properties are allowed in a model in a request
### Describe your problem(s)
My request is something like:
```json
{
    "serviceRequest": {
        "COMMAND": {
            "TYPE": "CHECK",
            "LANGUAGE1":"1",
            "MSISDN":"3232332",
            "MPIN":"1357"
        }
    },
    "userInfo": {
        "imei": "351665069414667:351665069414667",
        "USERID": "UA74dfa127-f921-4d4b-8d46-747c2f479c0f",
        "userLanguage": "1",
        "ostype": "ANDROID"
    }
}
```

I want that within COMMAND object other keys can also be present so how can i specify the same in open API?

Attaching my code for reference:

```yaml
openapi: 3.0.0
servers:
- url: http://localhost:9095/Mobiquity
info:
  description: 'This is a sample server Petstore server.  You can find out more about
    Swagger at [http://swagger.io](http://swagger.io) or on [irc.freenode.net, #swagger](http://swagger.io/irc/).  For
    this sample, you can use the api key `special-key` to test the authorization filters.'
  version: 1.0.0
  title: Swagger checkForUpdate New
  termsOfService: http://swagger.io/terms/
  contact:
    email: apiteam@swagger.io
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
tags:
- name: menu
  description: Everything about your callService
  externalDocs:
    description: Find out more
    url: http://swagger.io
x-wso2-basePath: /Mobiquity/1.0.0
x-wso2-request-interceptor: validateGlobalRequest
x-wso2-response-interceptor: validateGlobalResponse
x-wso2-production-endpoints:
        urls:
        - http://localhost:7099/Mobiquity/      		
paths:
  "/callJigsaw/V2":
    post:
      tags:
      - callJigsaw
      summary: check for update
      description: callJigsaw
      operationId: callJigsaw
      x-wso2-request-interceptor: validateRequestDemo
      x-wso2-response-interceptor: validateResponse
      responses:
        '200':
          description: successful operation
        '400':
          description: Invalid status value
      x-wso2-disable-security: true
  "/checkForUpdate/V2":
    post:
      tags:
      - checkForUpdate
      summary: check for update
      description: checkForUpdate
      operationId: checkForUpdate
      requestBody:
        "$ref": "#/components/schemas/moneyRequest"
      x-wso2-request-interceptor: validateRequest
      x-wso2-response-interceptor: validateGlobalResponse
      responses:
        '200':
          description: successful operation
        '400':
          description: Invalid status value
      x-wso2-disable-security: true
  "/CallBankingLogOut/1.0.0":
    post:
      tags:
      - call logout mockable
      summary: logout mockable
      description: logout mockable
      operationId: logout mockable
      x-wso2-production-endpoints:
        urls:
        - http://dbxp-mfsapps.mockable.io/
      responses:
        '200':
          description: successful operation
        '400':
          description: Invalid status value
      x-wso2-disable-security: true
  "/CallBankingLogOut/V2":
    post:
      tags:
      - logout
      summary: logout local
      description: logout
      operationId: logout
      x-wso2-production-endpoints:
        urls:
        - http://localhost:7099/Mobiquity/
      responses:
        '200':
          description: successful operation
        '400':
          description: Invalid status value
      x-wso2-disable-security: true	 
components:
  schemas:
    moneyRequest:
      type: object
      properties:
       serviceRequest:
         $ref: '#/components/schemas/serviceRequest'
      required:
        - serviceRequest
    serviceRequest:
      type: object
      properties:
        COMMAND:
          $ref: '#/components/schemas/COMMAND'
      additionalProperties:
        type: string    
      required:
       - COMMAND
    COMMAND:
      type: object
      additionalProperties:
        type: string
      properties:
        TYPE:
          type: string
        LANGUAGE1:
          type: string 
        MSISDN:
          type: string
      required:
       - TYPE
       - LANGUAGE1
       - MSISDN
       
  requestBodies:
    moneyRequest:
      content:
        application/json:
          schema:
            "$ref": "#/components/schemas/moneyRequest"
        application/xml:
          schema:
            "$ref": "#/components/schemas/moneyRequest"
      description: moneyRequest object that needs to be validated
      required: true    
```
I have used additionalProperties as stated above but they are not working
### How will you implement it

---

### LINKED ISSUE #1033: JSON schema validation should be improved
### Describe your problem(s)
Wrap .bal methods to java native codes

### How will you implement it

---

### LINKED ISSUE #1080: Schema Validation feature test cases are commented.
### Description:
Validation feature test cases should be enabled again.

### Environment details (with versions):
- OS:
- Client:
- Env (Docker/K8s):

---

### LINKED ISSUE #1081: Schema validator - everit related jar should be unpacked from the lib/dependencies
### Description:
Everit depends on large number of dependencies.

### Environment details (with versions):
- OS:
- Client:
- Env (Docker/K8s):

---

### LINKED ISSUE #1125: Issue occurred when the response validation is enabled
### Description:
There is an issue in the response validation flow.

### Steps to reproduce:
Enable validation config in micro-gw.conf
[validationConfig]
  enableRequestValidation = true 
  enableResponseValidation = true

### Environment details (with versions):
- OS:
- Client:
- Env (Docker/K8s):

---

### PR DESCRIPTION
**Pull request by hasuniea**
### Purpose
This PR fixes #1125 #1081 #1080 #1033 #936

### Issues
Fixes #1125 
Fixes #1081
Fixes #1080
Fixes #1033
Fixes #936

### Automation tests
 - Unit tests added: Yes/No
 - Integration tests added: Yes/No

### Tested environments

Not Tested

---
#### Maintainers: Check before merge
- [x] Assigned 'Type' label
- [x] Assigned the project
- [x] Validated respective github issues
- [x] Assigned milestone to the github issue(s)

### CODE REVIEW

File: tests/src/test/java/org/wso2/micro/gateway/tests/common/ResponseConstants.java [hunk 1]
```diff
@@ -25,16 +25,15 @@
...
-            + "  \"status\": \"available\"" + "}";
+    public static final String petByIdResponse = "{\"id\":2, \"category\":{\"id\":1, \"name\":\"John Doe\"}, " +
+            "\"name\":\"shre\", \"photoUrls\":[\"ArrayItem1\"], \"tags\":[{\"id\":1, \"name\":\"TfNSW\"}]," +
+            " \"status\":\"hello\"}";
+    public static final String petByIdResponseV1 = "{\"id\":2, \"category\":{\"id\":1, \"name\":\"John Doe\"}, " +
+            "\"name\":\"shre\", \"photoUrls\":[\"ArrayItem1\"], \"tags\":[{\"id\":1, \"name\":\"TfNSW\"}], " +
+            "\"status\":\"hello\"}";
+    public static final String getPetResponse = "{\"id\":2, \"category\":{\"id\":1, \"name\":\"John Doe\"}," +
+            " \"name\":\"shre\", \"photoUrls\":[\"ArrayItem1\"], \"tags\":[{\"id\":1, \"name\":\"TfNSW\"}]," +
+            " \"status\":\"hello\"}";
```
Comment (Rajith90) [inline tests/src/test/java/org/wso2/micro/gateway/tests/common/ResponseConstants.java]: Isn't these responses used by other test cases to validate

File: tests/src/test/java/org/wso2/micro/gateway/tests/extensions/OASAPIInvokeTestCase.java [hunk 2]
```diff
@@ -67,4 +68,9 @@ public void testApiInvokeWithJWT() throws Exception {
         Assert.assertEquals(response.getData(), ResponseConstants.petByIdResponse);
         Assert.assertEquals(response.getResponseCode(), 200, "Response code mismatched");
     }
+
+    @AfterClass
+    public void stop() throws Exception {
+        super.finalize();
+    }
```
Comment (Rajith90) [inline tests/src/test/java/org/wso2/micro/gateway/tests/extensions/OASAPIInvokeTestCase.java]: This test class no need to have after class. This will cause test failures

File: components/micro-gateway-core/src/main/java/org/wso2/micro/gateway/core/Constants.java [hunk 3]
```diff
@@ -58,7 +56,6 @@
     public static final String JSON_CONTENT = ".application/json.schema.$ref";
     public static final String SCHEMA = ".schema";
     public static final String EMPTY_ARRAY = "[]";
-    public static final String INTERNAL_ERROR_CODE = "500";
```
Comment (Rajith90) [inline components/micro-gateway-core/src/main/java/org/wso2/micro/gateway/core/Constants.java]: Isn't this constant have usage in https://github.com/wso2/product-microgateway/blob/master/components/micro-gateway-core/src/main/ballerina/src/gateway/filters/throttle_filter.bal#L186

Comment (hasuniea) [reply components/micro-gateway-core/src/main/java/org/wso2/micro/gateway/core/Constants.java]: It uses this constant 
https://github.com/wso2/product-microgateway/blob/master/components/micro-gateway-core/src/main/ballerina/src/gateway/constants/api_throttle_out_constants.bal#L21

File: tests/src/test/java/org/wso2/micro/gateway/tests/common/ResponseConstants.java (hunk 1 above)
Comment (hasuniea) [reply tests/src/test/java/org/wso2/micro/gateway/tests/common/ResponseConstants.java]: I checked other usages and verified it doesn't affect the functionality.

File: tests/src/test/java/org/wso2/micro/gateway/tests/extensions/OASAPIInvokeTestCase.java (hunk 2 above)
Comment (hasuniea) [reply tests/src/test/java/org/wso2/micro/gateway/tests/extensions/OASAPIInvokeTestCase.java]: fixed

File: components/micro-gateway-core/src/main/ballerina/src/gateway/filters/validation_filter.bal [hunk 4]
```diff
@@ -94,9 +94,14 @@
...
+             json newPayload = { fault: {
+                                    code: 400,
+                                    message: "Bad Request",
+                                    description: valResult.toString()
+                                } };
             http:Response res = new;
             res.statusCode = 400;
-            res.setPayload(valResult.toString());
+            res.setJsonPayload(newPayload);
             var rcal = caller->respond(res);
```
Comment (Rajith90) [inline components/micro-gateway-core/src/main/ballerina/src/gateway/filters/validation_filter.bal]: Handle the error scenario

File: components/micro-gateway-core/src/main/ballerina/src/gateway/filters/validation_filter.bal [hunk 5]
```diff
@@ -118,15 +124,22 @@
...
+         var valResult = responseValidate(resPath, reqMethod, responseCode, resPayload, servName);
          if (valResult is handle && stringutils:equalsIgnoreCase(valResult.toString(), VALIDATION_STATUS)) {
              return true;
          } else {
+             json newPayload = { fault: {
+                                        code: 500,
+                                        message: "Bad Response",
+                                        description: valResult.toString()
+                               } };
              response.statusCode = 500;
```
Comment (Rajith90) [inline components/micro-gateway-core/src/main/ballerina/src/gateway/filters/validation_filter.bal]: Lets try to use the constants if available in b7a http module

File: components/micro-gateway-core/src/main/java/org/wso2/micro/gateway/core/validation/Validate.java [hunk 6]
```diff
@@ -44,6 +44,7 @@
 import java.util.zip.ZipEntry;
 import java.util.zip.ZipInputStream;
 
+import static org.wso2.micro.gateway.core.Constants.EMPTY_ARRAY;
```
Comment (Rajith90) [inline components/micro-gateway-core/src/main/java/org/wso2/micro/gateway/core/validation/Validate.java]: Lets remove static imports

File: components/micro-gateway-core/src/main/java/org/wso2/micro/gateway/core/validation/Validate.java [hunk 7]
```diff
@@ -70,7 +71,12 @@ public static String validateRequest(String requestPath, String reqMethod, Strin
             return VALIDATED_STATUS;
         }
         String schema = extractSchemaFromRequest(requestPath, reqMethod, swagger);
-        return validateContent(payload, schema);
+        if (schema != null && !EMPTY_ARRAY.equals(schema) &&
```
Comment (Rajith90) [inline components/micro-gateway-core/src/main/java/org/wso2/micro/gateway/core/validation/Validate.java]: If schema is available and payload is null then, this will gives the status as true

File: components/micro-gateway-core/src/main/java/org/wso2/micro/gateway/core/validation/Validate.java [hunk 8]
```diff
@@ -125,13 +140,13 @@ private static String extractSchemaFromRequest(String resourcePath, String reque
...
                 Constants.OPEN_API).toString();
-        if (value != null && !value.equals(Constants.EMPTY_ARRAY)) {
+        if (value != null && !value.equals(EMPTY_ARRAY)) {
             //refer schema
             StringBuilder jsonPath = new StringBuilder();
             jsonPath.append(Constants.PATHS)
                     .append(resourcePath).append(Constants.BODY_CONTENT);
             schema = JsonPath.read(swagger, jsonPath.toString()).toString();
-            if (schema == null | Constants.EMPTY_ARRAY.equals(schema)) {
+            if (schema == null | EMPTY_ARRAY.equals(schema)) {
```
Comment (Rajith90) [inline components/micro-gateway-core/src/main/java/org/wso2/micro/gateway/core/validation/Validate.java]: use the || in if condition

File: pom.xml [hunk 9]
```diff
@@ -596,15 +601,15 @@
         <apache.commons.version>1.5.6.wso2v1</apache.commons.version>
         <everit.version>1.5.0.wso2.v1</everit.version>
         <jayway.jsonpath.version>2.4.0</jayway.jsonpath.version>
-        <com.google.guava.version>27.1-jre</com.google.guava.version>
+        <com.google.guava.version>27.0-jre</com.google.guava.version>
```
Comment (Rajith90) [inline pom.xml]: lets keep the new version

File: pom.xml [hunk 10]
```diff
@@ -596,15 +601,15 @@
...
         <commons-io.version>2.6</commons-io.version>
         <commons-lang3.version>3.9</commons-lang3.version>
-        <org.json.version>20160810</org.json.version>
         <com.jayway.jsonpath.version>2.4.0.wso2v2</com.jayway.jsonpath.version>
-        <json.orbit.version>3.0.0.wso2v1</json.orbit.version>
-        <jackson-data-bind.version>2.9.10.1</jackson-data-bind.version>
         <jackson-core.version>2.9.9</jackson-core.version>
+        <everit.version>1.5.0.wso2.v1</everit.version>
+        <fasterxml.jackson.databind.version>2.9.10</fasterxml.jackson.databind.version>
+        <json.orbit.version>3.0.0.wso2v1</json.orbit.version>
```
Comment (Rajith90) [inline pom.xml]: Lets remove the orbit

File: tests/src/test/resources/confs/validation.conf [hunk 11]
```diff
@@ -4,32 +4,31 @@ httpsPort=9595
...
-enableResponseValidation = true
+  [b7a.users.generalUser1]
+    password="5baa61e4c9b93f3f0682250b6cf8331b7ee68fd8"
 
 [apikey.tokenConfigs]
-issuer="https://localhost:9095/apikey"
-audience="http://org.wso2.apimgt/gateway"
-certificateAlias="ballerina"
-validateAllowedAPIs=true
+  issuer="https://localhost:9095/apikey"
```
Comment (AmaliMatharaarachchi) [inline tests/src/test/resources/confs/validation.conf]: Let's remove these configs since we can use the default values for this test case

File: tests/src/test/resources/confs/validation.conf [hunk 12]
```diff
@@ -4,32 +4,31 @@ httpsPort=9595
...
+   enabled=true
+   keyStorePath="${ballerina.home}/bre/security/ballerinaKeystore.p12"
+   keyStorePassword="ballerina"
+   issuer="https://localhost:9095/apikey"
+   audience="http://org.wso2.apimgt/gateway"
+   certificateAlias="ballerina"
+   validityTime=600
+[[apikey.issuer.api]]
+   name="PetStoreAPI"
+   versions="1.0.0"
```
Comment (AmaliMatharaarachchi) [inline tests/src/test/resources/confs/validation.conf]: We can remove these configs since we can use the default values for this test case.

File: tests/src/test/resources/confs/validation.conf [hunk 13]
```diff
@@ -4,32 +4,31 @@ httpsPort=9595
...
 
 [apikey.tokenConfigs]
-issuer="https://localhost:9095/apikey"
-audience="http://org.wso2.apimgt/gateway"
-certificateAlias="ballerina"
-validateAllowedAPIs=true
+  issuer="https://localhost:9095/apikey"
+  audience="http://org.wso2.apimgt/gateway"
+  certificateAlias="ballerina"
+  validateAllowedAPIs=true
```
Comment (AmaliMatharaarachchi) [inline tests/src/test/resources/confs/validation.conf]: Let's remove these configs since we can use the default values for this test case

Comment (hasuniea) [reply tests/src/test/resources/confs/validation.conf]: fixed

File: tests/src/test/resources/confs/validation.conf (hunk 12 above)
Comment (hasuniea) [reply tests/src/test/resources/confs/validation.conf]: fixed.

File: pom.xml (hunk 10 above)
Comment (hasuniea) [reply pom.xml]: removed the version.

File: pom.xml (hunk 9 above)
Comment (hasuniea) [reply pom.xml]: upgrade to previous version.

File: components/micro-gateway-core/src/main/java/org/wso2/micro/gateway/core/validation/Validate.java (hunk 8 above)
Comment (hasuniea) [reply components/micro-gateway-core/src/main/java/org/wso2/micro/gateway/core/validation/Validate.java]: fixed.

File: components/micro-gateway-core/src/main/java/org/wso2/micro/gateway/core/validation/Validate.java (hunk 7 above)
Comment (hasuniea) [reply components/micro-gateway-core/src/main/java/org/wso2/micro/gateway/core/validation/Validate.java]: fixed.

File: components/micro-gateway-core/src/main/java/org/wso2/micro/gateway/core/validation/Validate.java (hunk 6 above)
Comment (hasuniea) [reply components/micro-gateway-core/src/main/java/org/wso2/micro/gateway/core/validation/Validate.java]: removed.

File: components/micro-gateway-core/src/main/ballerina/src/gateway/filters/validation_filter.bal (hunk 5 above)
Comment (hasuniea) [reply components/micro-gateway-core/src/main/ballerina/src/gateway/filters/validation_filter.bal]: fixed.

File: components/micro-gateway-core/src/main/ballerina/src/gateway/filters/validation_filter.bal (hunk 4 above)
Comment (hasuniea) [reply components/micro-gateway-core/src/main/ballerina/src/gateway/filters/validation_filter.bal]: handled the error.
