### PR TITLE
No proper error response when the provided JWT cannot be parsed.

### LINKED ISSUE #1894: Auth Failures are not published to the analytics portal.
### Description:
If the authentication failure happens when an exception is thrown (Unclassified Authentication Failure), analytics event is not published.

Here is a sample stack trace of such auth failure.

```
SEVERE: Exception while executing runnable io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$1HalfClosed@259e9e33
enforcer_1  | java.lang.SecurityException: Not a JWT token. Failed to decode the token header.
enforcer_1  | 	at org.wso2.choreo.connect.enforcer.security.jwt.JWTAuthenticator.authenticate(JWTAuthenticator.java:108)
enforcer_1  | 	at org.wso2.choreo.connect.enforcer.security.AuthFilter.authenticate(AuthFilter.java:123)
enforcer_1  | 	at org.wso2.choreo.connect.enforcer.security.AuthFilter.handleRequest(AuthFilter.java:105)
enforcer_1  | 	at org.wso2.choreo.connect.enforcer.api.API.executeFilterChain(API.java:41)
enforcer_1  | 	at org.wso2.choreo.connect.enforcer.api.RestAPI.process(RestAPI.java:99)
enforcer_1  | 	at org.wso2.choreo.connect.enforcer.server.RequestHandler.process(RequestHandler.java:60)
enforcer_1  | 	at org.wso2.choreo.connect.enforcer.grpc.ExtAuthService.check(ExtAuthService.java:50)
enforcer_1  | 	at io.envoyproxy.envoy.service.auth.v3.AuthorizationGrpc$MethodHandlers.invoke(AuthorizationGrpc.java:245)
enforcer_1  | 	at io.grpc.stub.ServerCalls$UnaryServerCallHandler$UnaryServerCallListener.onHalfClose(ServerCalls.java:180)
enforcer_1  | 	at io.grpc.internal.ServerCallImpl$ServerStreamListenerImpl.halfClosed(ServerCallImpl.java:331)
enforcer_1  | 	at io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$1HalfClosed.runInContext(ServerImpl.java:814)
enforcer_1  | 	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
enforcer_1  | 	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123)
enforcer_1  | 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
enforcer_1  | 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
enforcer_1  | 	at java.base/java.lang.Thread.run(Unknown Source)
enforcer_1  | Caused by: java.text.ParseException: Invalid JWS header: Invalid JSON: Unexpected token 
enforcer_1  | 	at com.nimbusds.jose.JWSObject.<init>(JWSObject.java:155)
enforcer_1  | 	at com.nimbusds.jwt.SignedJWT.<init>(SignedJWT.java:78)
enforcer_1  | 	at com.nimbusds.jwt.SignedJWT.parse(SignedJWT.java:116)
enforcer_1  | 	at org.wso2.choreo.connect.enforcer.security.jwt.JWTAuthenticator.getSignedJwt(JWTAuthenticator.java:585)
enforcer_1  | 	at org.wso2.choreo.connect.enforcer.security.jwt.JWTAuthenticator.authenticate(JWTAuthenticator.java:106)
enforcer_1  | 	... 15 more
enforcer_1  | 

```

### Steps to reproduce:
Provide an invalid token such that it is not a JWT token format.

### Affected Product Version:
choreo-connect-0.9.0 alpha

### Environment details (with versions):
- OS:
- Client:
- Env (Docker/K8s):

---

### LINKED ISSUE #1913: No Proper Error Message, when the provided JWT cannot be parsed.
### Description:

When this scenario happens, following error message can be seen within the enforcer log

```
SEVERE: Exception while executing runnable io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$1HalfClosed@259e9e33
enforcer_1  | java.lang.SecurityException: Not a JWT token. Failed to decode the token header.
enforcer_1  | 	at org.wso2.choreo.connect.enforcer.security.jwt.JWTAuthenticator.authenticate(JWTAuthenticator.java:108)
enforcer_1  | 	at org.wso2.choreo.connect.enforcer.security.AuthFilter.authenticate(AuthFilter.java:123)
enforcer_1  | 	at org.wso2.choreo.connect.enforcer.security.AuthFilter.handleRequest(AuthFilter.java:105)
enforcer_1  | 	at org.wso2.choreo.connect.enforcer.api.API.executeFilterChain(API.java:41)
enforcer_1  | 	at org.wso2.choreo.connect.enforcer.api.RestAPI.process(RestAPI.java:99)
enforcer_1  | 	at org.wso2.choreo.connect.enforcer.server.RequestHandler.process(RequestHandler.java:60)
enforcer_1  | 	at org.wso2.choreo.connect.enforcer.grpc.ExtAuthService.check(ExtAuthService.java:50)
enforcer_1  | 	at io.envoyproxy.envoy.service.auth.v3.AuthorizationGrpc$MethodHandlers.invoke(AuthorizationGrpc.java:245)
enforcer_1  | 	at io.grpc.stub.ServerCalls$UnaryServerCallHandler$UnaryServerCallListener.onHalfClose(ServerCalls.java:180)
enforcer_1  | 	at io.grpc.internal.ServerCallImpl$ServerStreamListenerImpl.halfClosed(ServerCallImpl.java:331)
enforcer_1  | 	at io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$1HalfClosed.runInContext(ServerImpl.java:814)
enforcer_1  | 	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
enforcer_1  | 	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123)
enforcer_1  | 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
enforcer_1  | 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
enforcer_1  | 	at java.base/java.lang.Thread.run(Unknown Source)
enforcer_1  | Caused by: java.text.ParseException: Invalid JWS header: Invalid JSON: Unexpected token 
enforcer_1  | 	at com.nimbusds.jose.JWSObject.<init>(JWSObject.java:155)
enforcer_1  | 	at com.nimbusds.jwt.SignedJWT.<init>(SignedJWT.java:78)
enforcer_1  | 	at com.nimbusds.jwt.SignedJWT.parse(SignedJWT.java:116)
enforcer_1  | 	at org.wso2.choreo.connect.enforcer.security.jwt.JWTAuthenticator.getSignedJwt(JWTAuthenticator.java:585)
enforcer_1  | 	at org.wso2.choreo.connect.enforcer.security.jwt.JWTAuthenticator.authenticate(JWTAuthenticator.java:106)
enforcer_1  | 	... 15 more
enforcer_1  | 
```
And the error response user get is the generic error response of `403 : Forbidden`

### Steps to reproduce:

Invoke the API with Authorization header set as some random string (`Authorization: Bearer aaa.bbb.ccc`)

### Affected Product Version:
choreo-connect 0.9.0-alpha

### Environment details (with versions):
- OS:
- Client:
- Env (Docker/K8s): Docker-compose

---

### PR DESCRIPTION
**Pull request by VirajSalaka**
### Purpose

$subject

### Issues

Fixes #1913
Fixes #1894 

### Automation tests
 - Unit tests added: No
 - Integration tests added: Yes

### Tested environments

Docker compose

---
#### Maintainers: Check before merge
- [x] Assigned 'Type' label
- [x] Assigned the project
- [x] Validated respective github issues
- [x] Assigned milestone to the github issue(s)

### CODE REVIEW

File: enforcer/src/main/java/org/wso2/choreo/connect/enforcer/security/jwt/JWTAuthenticator.java [hunk 1]
```diff
@@ -101,12 +101,14 @@ public AuthenticationContext authenticate(RequestContext requestContext) throws
...
         ResourceConfig matchingResource = requestContext.getMatchedResourcePath();
-        String httpMethod = requestContext.getMatchedResourcePath().getMethod().toString();
         SignedJWTInfo signedJWTInfo;
         try {
             signedJWTInfo = getSignedJwt(jwtToken);
         } catch (ParseException | IllegalArgumentException e) {
-            throw new SecurityException("Not a JWT token. Failed to decode the token header.", e);
+            log.error("Failed to decode the token header", e);
+            throw new APISecurityException(APIConstants.StatusCodes.UNAUTHENTICATED.getCode(),
+                    APISecurityConstants.API_AUTH_GENERAL_ERROR,
```
Comment (Rajith90) [inline enforcer/src/main/java/org/wso2/choreo/connect/enforcer/security/jwt/JWTAuthenticator.java:110]: This is invalid token, We should send invalid token error

Comment (VirajSalaka) [reply enforcer/src/main/java/org/wso2/choreo/connect/enforcer/security/jwt/JWTAuthenticator.java]: added via https://github.com/wso2/product-microgateway/pull/1914/commits/4b567b0841950c3eba864b2a3ab89fe836c73a75

**Review by Rajith90 — APPROVED** [review]

**Review by Rajith90 — APPROVED** [review]
