### PR TITLE
Change the REST API Request process

### LINKED ISSUE #2662: Startup Fails when API Manager has a large number of APIs created.
### Description:
When there are large number of APIs (> 6000) in the API Manager, and distribution contains like ~20 adapters (to handle different environments) the startup takes a considerable amount of time as the API Manager takes a lot of time to process request coming to `/internal/data/v1/apis` . 

### Steps to reproduce:
Create a large number of APIs ~7000 and run ~20 adapters. Then observe the time taken to process '/apis endpoint

### Affected Product Version:
Choreo-connect 1.0.0, 1.1.0-m1

### Environment details (with versions):
- API Manager : 4.0.0

---

### PR DESCRIPTION
**Pull request by VirajSalaka**
### Issues

Fixes #2662

### Automation tests
 - Unit tests added: No
 - Integration tests added: No (Existing set of tests covers the behavior)

### Tested environments

Not Tested

---
#### Maintainers: Check before merge
- [ ] Assigned 'Type' label
- [ ] Assigned the project
- [ ] Validated respective github issues
- [ ] Assigned milestone to the github issue(s)

### CODE REVIEW

File: adapter/pkg/synchronizer/client_pool.go [hunk 1]
```diff
@@ -0,0 +1,133 @@
...
+type processHTTPRequest func(*http.Request, *string, []string, chan SyncAPIResponse) bool
+
+func (w *worker) ProcessFunction() {
+	for workerReq := range w.internalQueue {
+		responseReceived := w.processFunc(&workerReq.Req, workerReq.APIUUID, workerReq.labels, workerReq.SyncAPIRespChannel)
+		if !responseReceived {
+			// TODO: (VirajSalaka) make it configurable
+			time.Sleep(5 * time.Second)
+		}
+
```
Comment (VirajSalaka) [inline adapter/pkg/synchronizer/client_pool.go:54]: new line

File: adapter/pkg/synchronizer/client_pool.go [hunk 2]
```diff
@@ -0,0 +1,133 @@
...
+	timeout     time.Duration
+}
+
+type processHTTPRequest func(*http.Request, *string, []string, chan SyncAPIResponse) bool
+
+func (w *worker) ProcessFunction() {
+	for workerReq := range w.internalQueue {
+		responseReceived := w.processFunc(&workerReq.Req, workerReq.APIUUID, workerReq.labels, workerReq.SyncAPIRespChannel)
+		if !responseReceived {
+			// TODO: (VirajSalaka) make it configurable
```
Comment (VirajSalaka) [inline adapter/pkg/synchronizer/client_pool.go:51]: fix TODO

File: adapter/config/default_config.go [hunk 3]
```diff
@@ -288,6 +288,10 @@ var defaultConfig = &Config{
 		HTTPClient: httpClient{
 			RequestTimeOut: 30,
 		},
+		ControlPlaneRequestWorkerPool: controlPlaneRequestWorkerPool{
+			PoolSize:           4,
+			QueueSizePerWorker: 1000,
```
Comment (VirajSalaka) [inline adapter/config/default_config.go:293]: QueueSizePerPool

File: adapter/pkg/synchronizer/client_pool.go [hunk 4]
```diff
@@ -0,0 +1,176 @@
+/*
```
Comment (renuka-fernando) [inline adapter/pkg/synchronizer/client_pool.go:1]: License header

File: adapter/pkg/synchronizer/client_pool.go [hunk 5]
```diff
@@ -0,0 +1,176 @@
...
+	id              int
+	internalQueue   <-chan workerRequest
+	processFunc     processHTTPRequest
+	delayAfterFault time.Duration
+	// done          *sync.WaitGroup
+	// work          chan Work
+	// quit          chan bool
+}
+
+// WorkerRequest is the task which can be submitted to the pool.
```
Comment (renuka-fernando) [inline adapter/pkg/synchronizer/client_pool.go:29]:
```suggestion
// workerRequest is the task which can be submitted to the pool.
```

File: adapter/pkg/synchronizer/apis_fetcher.go [hunk 6]
```diff
@@ -60,18 +58,99 @@ const (
 // FetchAPIs pulls the API artifact calling to the API manager
 // API Manager returns a .zip file as a response and this function
 // returns a byte slice of that ZIP file.
```
Comment (VirajSalaka) [inline adapter/pkg/synchronizer/apis_fetcher.go:60]: Fix the comment.

File: adapter/pkg/adapter/adapter.go [hunk 7]
```diff
@@ -18,26 +18,20 @@
...
 	if len(envs) > 0 {
 		// If the envrionment labels are present, call the controle plane with labels.
 		logger.LoggerAdapter.Debugf("Environments label present: %v", envs)
-		go synchronizer.FetchAPIs(id, envs, c, serviceURL, userName, password, skipSSL, truststoreLocation,
-			endpoint, sendType, apiUUIDList, requestTimeOut, queryParamMap)
+		go synchronizer.FetchAPIs(id, envs, c, endpoint, sendType, apiUUIDList, queryParamMap)
 	} else {
 		// If the environments are not give, fetch the APIs from default envrionment
-		logger.LoggerAdapter.Debug("Environments label  NOT present. Hence adding \"default\"")
-		envs = append(envs, "default")
```
Comment (VirajSalaka) [inline adapter/pkg/adapter/adapter.go:39]: Populating default label is required.

Comment (VirajSalaka) [inline adapter/pkg/adapter/adapter.go:39]: populate Default label again because it is a mandatory field for the API Manager Internal rest APIs.

File: adapter/pkg/synchronizer/client_pool.go [hunk 8]
```diff
@@ -0,0 +1,188 @@
...
+type workerRequest struct {
+	Req                http.Request
+	APIUUID            *string
+	labels             []string
+	SyncAPIRespChannel chan SyncAPIResponse
+}
+
+// pool is the worker pool which is handling
+type pool struct {
+	// TODO: (VirajSalaka) remove timeout
```
Comment (VirajSalaka) [inline adapter/pkg/synchronizer/client_pool.go:52]: Check and remove the todo statement

File: adapter/pkg/synchronizer/client_pool.go [hunk 9]
```diff
@@ -0,0 +1,188 @@
...
+	internalQueue      chan workerRequest
+	workers            []*worker
+	quit               chan bool
```
Comment (VirajSalaka) [inline adapter/pkg/synchronizer/client_pool.go:55]: Remove quit channel

File: adapter/pkg/synchronizer/client_pool.go [hunk 10]
```diff
@@ -0,0 +1,188 @@
...
+	oncePoolInitiated sync.Once
+)
+
+// InitializeWorkerPool creates the Worker Pool used for the Control Plane Rest API invocations.
+// maxWorkers indicate the maximum number of parallel workers sending requests to the control plane.
+// jobQueueCapacity indicate the maximum number of requests can kept inside a single worker's queue.
+// delayForFaultRequests indicate the delay a worker enforce (in seconds) when a fault response is received.
+func InitializeWorkerPool(maxWorkers, jobQueueCapacity int, delayForFaultRequests time.Duration, trustStoreLocation string,
+	skipSSL bool, requestTimeout, retryInterval time.Duration, serviceURL, username, password string) {
+	// TODO: (VirajSalaka) Think on whether this could be moved to global adapter seamlessly.
```
Comment (VirajSalaka) [inline adapter/pkg/synchronizer/client_pool.go:92]: remove todo statement.

File: adapter/pkg/synchronizer/client_pool.go [hunk 11]
```diff
@@ -0,0 +1,188 @@
...
+	workerPool        *pool
+	oncePoolInitiated sync.Once
+)
+
+// InitializeWorkerPool creates the Worker Pool used for the Control Plane Rest API invocations.
+// maxWorkers indicate the maximum number of parallel workers sending requests to the control plane.
+// jobQueueCapacity indicate the maximum number of requests can kept inside a single worker's queue.
+// delayForFaultRequests indicate the delay a worker enforce (in seconds) when a fault response is received.
+func InitializeWorkerPool(maxWorkers, jobQueueCapacity int, delayForFaultRequests time.Duration, trustStoreLocation string,
+	skipSSL bool, requestTimeout, retryInterval time.Duration, serviceURL, username, password string) {
```
Comment (VirajSalaka) [inline adapter/pkg/synchronizer/client_pool.go:91]: retryInterval usage?

File: adapter/pkg/synchronizer/client_pool.go [hunk 12]
```diff
@@ -0,0 +1,188 @@
...
+		internalQueue: requestChannel,
+		workers:       workers,
+		quit:          make(chan bool),
+	}
+}
+
+// Enqueue Tries to enqueue but fails if queue is full
+func (q *pool) Enqueue(req workerRequest) bool {
+	if len(q.internalQueue) > cap(q.internalQueue)/10*8 {
+		loggers.LoggerSync.Errorf("Queue size for worker pool is at %d."+
```
Comment (VirajSalaka) [inline adapter/pkg/synchronizer/client_pool.go:152]: Log level should be mentioned with Major.

File: adapter/pkg/synchronizer/client_pool.go [hunk 13]
```diff
@@ -0,0 +1,188 @@
...
+	return &pool{
+		internalQueue: requestChannel,
+		workers:       workers,
+		quit:          make(chan bool),
+	}
+}
+
+// Enqueue Tries to enqueue but fails if queue is full
+func (q *pool) Enqueue(req workerRequest) bool {
+	if len(q.internalQueue) > cap(q.internalQueue)/10*8 {
```
Comment (VirajSalaka) [inline adapter/pkg/synchronizer/client_pool.go:151]: Put a comment why this does not hit when a burst of api deploy events are triggered.

File: adapter/pkg/synchronizer/client_pool.go [hunk 14]
```diff
@@ -0,0 +1,188 @@
...
+		loggers.LoggerSync.Errorf("Queue size for worker pool is at %d."+
+			"Please check the reason for control plane request failures", len(q.internalQueue))
+	} else if len(q.internalQueue) > cap(q.internalQueue)/10*5 {
+		loggers.LoggerSync.Warnf("Queue size for worker pool is at %d."+
+			"Please check the reason for control plane request failures", len(q.internalQueue))
+	}
+	select {
+	case q.internalQueue <- req:
```
Comment (VirajSalaka) [inline adapter/pkg/synchronizer/client_pool.go:159]: check if this returns false if the capacity is filled.

File: adapter/pkg/synchronizer/client_pool.go [hunk 15]
```diff
@@ -0,0 +1,188 @@
...
+		return true
+	default:
+		return false
+	}
+}
+
+// EnqueueWithTimeout Tries to enqueue but fails if queue becomes not vacant within the defined period of time.
+func (q *pool) EnqueueWithTimeout(req workerRequest) bool {
```
Comment (VirajSalaka) [inline adapter/pkg/synchronizer/client_pool.go:167]: Remove this.

File: adapter/internal/synchronizer/apis_fetcher.go [hunk 16]
```diff
@@ -184,9 +183,7 @@ func FetchAPIsFromControlPlane(updatedAPIID string, updatedEnvs []string) {
 		} else {
 			// Keep the iteration still until all the envrionment response properly.
 			logger.LoggerSync.Errorf("Error occurred while fetching data from control plane: %v", data.Err)
```
Comment (VirajSalaka) [inline adapter/internal/synchronizer/apis_fetcher.go:185]: Include API ID.

Comment (VirajSalaka) [reply adapter/internal/synchronizer/apis_fetcher.go:185]: Mention that it starts retrying.

File: adapter/pkg/synchronizer/apis_fetcher.go [hunk 17]
```diff
@@ -161,52 +219,13 @@ func FetchAPIs(id *string, gwLabel []string, c chan SyncAPIResponse, serviceURL
...
 }
 
 // RetryFetchingAPIs function keeps retrying to fetch APIs from runtime-artifact endpoint.
-func RetryFetchingAPIs(c chan SyncAPIResponse, serviceURL string, userName string, password string, skipSSL bool,
-	truststoreLocation string, retryInterval time.Duration, data SyncAPIResponse, endpoint string, sendType bool,
-	requestTimeOut time.Duration, queryParamMap map[string]string) {
+func RetryFetchingAPIs(c chan SyncAPIResponse, data SyncAPIResponse, endpoint string, sendType bool,
+	queryParamMap map[string]string) {
+	retryInterval := workerPool.controlPlaneParams.retryInterval
 	go func(d SyncAPIResponse) {
```
Comment (VirajSalaka) [inline adapter/pkg/synchronizer/apis_fetcher.go:229]: check the possibility of removing go routine as it is already stays within a go routine.

File: adapter/config/default_config.go [hunk 18]
```diff
@@ -288,6 +288,10 @@ var defaultConfig = &Config{
 		HTTPClient: httpClient{
 			RequestTimeOut: 30,
 		},
+		RequestWorkerPool: requestWorkerPool{
+			PoolSize:         4,
+			QueueSizePerPool: 1000,
```
Comment (VirajSalaka) [inline adapter/config/default_config.go:293]: PauseTimeAfterFailure configuration field.

File: adapter/pkg/synchronizer/apis_fetcher.go [hunk 19]
```diff
@@ -57,21 +55,101 @@ const (
...
+	// If adding task to the pool cannot be done, the whole thread hangs here.
+	workerPool.Enqueue(workerReq)
+}
+
+// SendRequestToControlPlane is the function triggered to send the request to the control plane.
+// It returns true if a response is received from the api manager.
+func SendRequestToControlPlane(req *http.Request, apiID *string, gwLabels []string, c chan SyncAPIResponse,
+	client *http.Client) bool {
+	// Make the request
+	logger.LoggerSync.Debug("Sending the control plane request")
```
Comment (VirajSalaka) [inline adapter/pkg/synchronizer/apis_fetcher.go:91]: API ID

File: adapter/pkg/synchronizer/apis_fetcher.go [hunk 20]
```diff
@@ -57,21 +55,101 @@ const (
...
+	// For successful response, return the byte slice and nil as error
+	if resp.StatusCode == http.StatusOK {
+		respSyncAPI.Err = nil
+		respSyncAPI.Resp = respBytes
+		c <- respSyncAPI
+		return true
+	}
+	// If the response is not successful, create a new error with the response and log it and return
+	// Ex: for 401 scenarios, 403 scenarios.
+	logger.LoggerSync.Errorf("Failure response: %v", string(respBytes))
```
Comment (VirajSalaka) [inline adapter/pkg/synchronizer/apis_fetcher.go:134]: from controlplane

File: adapter/pkg/synchronizer/client_pool.go (hunk 14 above)
Comment (VirajSalaka) [reply adapter/pkg/synchronizer/client_pool.go:159]: it is getting blocked.

File: adapter/pkg/synchronizer/client_pool.go (hunk 11 above)
Comment (VirajSalaka) [reply adapter/pkg/synchronizer/client_pool.go:91]: It is used for the retry interval engaged for the fault requests which needs to be retried.

File: adapter/pkg/synchronizer/client_pool.go (hunk 12 above)
Comment (VirajSalaka) [reply adapter/pkg/synchronizer/client_pool.go]: this is removed.

File: adapter/pkg/synchronizer/apis_fetcher.go [hunk 21]
```diff
@@ -155,70 +212,34 @@ func FetchAPIs(id *string, gwLabel []string, c chan SyncAPIResponse, serviceURL
...
-	respSyncAPI.ErrorCode = resp.StatusCode
-	c <- respSyncAPI
-	return
-}
+	logger.LoggerSync.Debugf("Time Duration for retrying: %v", retryInterval*time.Second)
+	time.Sleep(retryInterval * time.Second)
+	logger.LoggerSync.Infof("Retrying to fetch API data from control plane for the API %q.", data.APIUUID)
+	channelFillPercentage := float64(len(workerPool.internalQueue)) / float64(cap(workerPool.internalQueue)) * 100
+	logger.LoggerSync.Infof("Workerpool channel size as a percentage is : %f", channelFillPercentage)
+	FetchAPIs(&data.APIUUID, data.GatewayLabels, c, endpoint, sendType, nil, queryParamMap)
```
Comment (VajiraPrabuddhaka) [inline adapter/pkg/synchronizer/apis_fetcher.go:242]: Do we have a log indicating that the retry attempt successful?

Comment (VirajSalaka) [reply adapter/pkg/synchronizer/apis_fetcher.go:242]: https://github.com/wso2/product-microgateway/blob/45532a6055d0588e4a774430ab84b32753166ecd/adapter/internal/synchronizer/apis_fetcher.go#L175
We improved the log such that APIID is included too.

Comment (VajiraPrabuddhaka) [reply adapter/pkg/synchronizer/apis_fetcher.go:242]: Ok got it.. 
Thanks..

File: adapter/internal/synchronizer/apis_fetcher.go [hunk 22]
```diff
@@ -165,28 +165,25 @@ func FetchAPIsFromControlPlane(updatedAPIID string, updatedEnvs []string) {
...
 		} else if data.ErrorCode >= 400 && data.ErrorCode < 500 {
-			logger.LoggerSync.Errorf("Error occurred when retrieving APIs from control plane: %v", data.Err)
+			logger.LoggerSync.Errorf("Error occurred when retrieving API %q from control plane: %v", updatedAPIID, data.Err)
 			health.SetControlPlaneRestAPIStatus(false)
 		} else {
 			// Keep the iteration still until all the envrionment response properly.
-			logger.LoggerSync.Errorf("Error occurred while fetching data from control plane: %v", data.Err)
-			sync.RetryFetchingAPIs(c, serviceURL, userName, password, skipSSL, truststoreLocation, retryInterval,
-				data, sync.RuntimeArtifactEndpoint, true, requestTimeOut, queryParamMap)
+			logger.LoggerSync.Errorf("Error occurred while fetching data from control plane for the API %q: %v. Retrying again.", updatedAPIID, data.Err)
```
Comment (VajiraPrabuddhaka) [inline adapter/internal/synchronizer/apis_fetcher.go:185]:
```suggestion
			logger.LoggerSync.Errorf("Error occurred while fetching data from control plane for the API %q: %v. Hence retrying..", updatedAPIID, data.Err)
```

File: adapter/pkg/synchronizer/apis_fetcher.go [hunk 23]
```diff
@@ -155,70 +212,34 @@ func FetchAPIs(id *string, gwLabel []string, c chan SyncAPIResponse, serviceURL
...
-		c <- respSyncAPI
-		return
-	}
+	return req
+}
 
-	// get the response in the form of a byte slice
-	respBytes, err = ioutil.ReadAll(resp.Body)
+// RetryFetchingAPIs function keeps retrying to fetch APIs from runtime-artifact endpoint.
+func RetryFetchingAPIs(c chan SyncAPIResponse, data SyncAPIResponse, endpoint string, sendType bool,
```
Comment (VajiraPrabuddhaka) [inline adapter/pkg/synchronizer/apis_fetcher.go:227]: does this always fetch a single API?

**Review by VajiraPrabuddhaka — APPROVED** [review]
LGTM

**Comment by choreo-cicd** [comment]
[failed] DataplaneE1 cluster : dev-deployment-v2 : 20220512.10

**Comment by choreo-cicd** [comment]
[failed] Controlplane cluster : dev-deployment-v2 : 20220512.10

**Comment by choreo-cicd** [comment]
[failed] DataplaneE2 cluster : dev-deployment-v2 : 20220512.10

**Comment by choreo-cicd** [comment]
[succeeded] Controlplane cluster : dev-deployment-v2 : 20220513.9

**Comment by choreo-cicd** [comment]
[succeeded] DataplaneE1 cluster : dev-deployment-v2 : 20220513.9

**Comment by choreo-cicd** [comment]
[succeeded] DataplaneE2 cluster : dev-deployment-v2 : 20220513.9

**Comment by choreo-cicd** [comment]
[failed] DataplaneE1 cluster : stage-deployment-v2 : 20220518.3

**Comment by choreo-cicd** [comment]
[succeeded] DataplaneE1 cluster : stage-deployment-v2 : 20220518.5

**Comment by choreo-cicd** [comment]
[succeeded] Controlplane cluster : prod-deployment-v2 : 20220523.1
