### PR TITLE
[Bug-Fix] Avoid Unwanted headers/query parameters being forwarded to the backend

### LINKED ISSUE #2572: Avoid Unwanted headers/query parameters being forwarded to the backend.
### Description:

There can be headers which are not supposed to forwarded to backend as well as in the throttle publish event. 

### Steps to reproduce:
Invoke API with APIKey. 
And check the recieved set of headers in the backend. 

### Affected Product Version:
choreo-connect-1.0.0-rc1

### Environment details (with versions):
- OS:
- Client:
- Env (Docker/K8s):

---

### PR DESCRIPTION
**Pull request by VirajSalaka**
### Purpose
bug fix: 
1. Stop sending the apiKey to backend (as a header and as a queryParam)

2. Stop sending authentication token/ apikey value within the throttle event

With this fix, users may be able to remove, modify query parameters using custom filters as well.

### Issues

Fixes #2572 

### Automation tests
 - Unit tests added: No
 - Integration tests added: No

### Tested environments

Not Tested

---
#### Maintainers: Check before merge
- [x] Assigned 'Type' label
- [x] Assigned the project
- [x] Validated respective github issues
- [x] Assigned milestone to the github issue(s)

### CODE REVIEW

File: enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/security/jwt/APIKeyAuthenticator.java [hunk 1]
```diff
@@ -104,11 +104,16 @@ private static String getAPIKeyFromRequest(RequestContext requestContext) {
                     // key must exist in specified location
                     if (APIConstants.SWAGGER_API_KEY_IN_HEADER.equalsIgnoreCase(securitySchemaDefinition.getIn())) {
                         if (requestContext.getHeaders().containsKey(securitySchemaDefinition.getName())) {
+                            // Remove the apiKey header being forwarded to the backend.
```
Comment (AmaliMatharaarachchi) [inline enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/security/jwt/APIKeyAuthenticator.java:107]: for authorizion header removal, we do it in this level. not in auth filter level. I'm wondering whether this should also be removed in this level

Comment (AmaliMatharaarachchi) [reply enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/security/jwt/APIKeyAuthenticator.java:107]: https://github.com/wso2/product-microgateway/blob/1e53dfa16ee0ecce7c43594927e5d1444772dc5c/enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/api/RestAPI.java#L163

File: enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/security/jwt/InternalAPIKeyAuthenticator.java [hunk 2]
```diff
@@ -98,6 +98,8 @@ public AuthenticationContext authenticate(RequestContext requestContext) throws
                 String internalKey = extractInternalKey(requestContext);
                 // Remove internal key from outbound request
                 requestContext.getRemoveHeaders().add(securityParam);
+                // Avoid internal key being published to the Traffic Manager
+                requestContext.getProtectedHeaders().add(securityParam);
```
Comment (AmaliMatharaarachchi) [inline enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/security/jwt/InternalAPIKeyAuthenticator.java:102]: both should be added outside of the auth filters imho

**Comment by AmaliMatharaarachchi** [comment]
Shall we add integration tests for this?

File: enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/grpc/ExtAuthService.java [hunk 3]
```diff
@@ -180,4 +194,34 @@ private int getCode(int statusCode) {
...
+                if (queryParamsToRemove.contains(queryParam)) {
+                    continue;
+                }
+                if (count == 0) {
+                    requestPathBuilder.append("?");
+                } else {
+                    requestPathBuilder.append("&");
+                }
+                requestPathBuilder.append(queryParam);
+                if (queryParamMap.get(queryParam) != null) {
```
Comment (AmaliMatharaarachchi) [inline enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/grpc/ExtAuthService.java:219]: Is it okay for query value being an empty string? Just to clarify.

File: enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/security/jwt/APIKeyAuthenticator.java (hunk 1 above)
Comment (VirajSalaka) [reply enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/security/jwt/APIKeyAuthenticator.java:107]: Doing it outside auth filter is not practical in this case, because the header name is resolved in this level.

Comment (VirajSalaka) [reply enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/security/jwt/APIKeyAuthenticator.java:107]: If that is the case, whole process needs to be restructured rather than fixing the bug.

File: enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/grpc/ExtAuthService.java (hunk 3 above)
Comment (VirajSalaka) [reply enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/grpc/ExtAuthService.java:219]: https://www.rfc-editor.org/rfc/rfc3986#section-3.4 as per spec, it does not limit

File: enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/api/RestAPI.java [hunk 4]
```diff
@@ -165,9 +166,13 @@ public ResponseObject process(RequestContext requestContext) {
             String authHeaderName = FilterUtils.getAuthHeaderName(requestContext);
             requestContext.getRemoveHeaders().add(authHeaderName);
         }
+        // Authorization Header should not be included in the throttle publishing event.
+        requestContext.getProtectedHeaders().add(FilterUtils.getAuthHeaderName(requestContext));
```
Comment (praminda) [inline enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/api/RestAPI.java:170]: why can't we just use removeHeaders for this purpose?

File: enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/grpc/ExtAuthService.java [hunk 5]
```diff
@@ -140,6 +143,17 @@ private CheckResponse buildResponse(CheckRequest request, ResponseObject respons
...
             OkHttpResponse.Builder okResponseBuilder = OkHttpResponse.newBuilder();
+
+            if (responseObject.getQueryParamsToRemove().size() > 0) {
+                String constructedPath = constructQueryParamString(responseObject.getRequestPath(),
+                        responseObject.getQueryParamMap(), responseObject.getQueryParamsToRemove());
+                HeaderValueOption headerValueOption = HeaderValueOption.newBuilder()
+                        .setHeader(HeaderValue.newBuilder().setKey(APIConstants.PATH_HEADER).setValue(constructedPath)
+                                .build())
+                        .build();
+                okResponseBuilder.addHeaders(headerValueOption);
```
Comment (praminda) [inline enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/grpc/ExtAuthService.java:154]: Better to add a comment here  explaining what we are doing in this piece of code and what we are trying to avoid by this.

File: enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/api/RestAPI.java [hunk 6]
```diff
@@ -288,4 +286,43 @@ private void loadCustomFilters(APIConfig apiConfig) {
...
+                    requestContext.getRemoveHeaders().add(schema.getName());
+                    continue;
+                }
+                if ("query".equals(schema.getIn())) {
+                    requestContext.getQueryParamsToRemove().add(schema.getName());
+                }
+            }
+        }
+
+        //Internal-Key credential is considered to be protected headers, such that the header would not be sent
```
Comment (praminda) [inline enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/api/RestAPI.java:311]:
```suggestion
        // Internal-Key credential is considered to be protected headers, such that the header would not be sent
```

File: enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/api/RestAPI.java (hunk 4 above)
Comment (VirajSalaka) [reply enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/api/RestAPI.java]: Because if the user enables forwarding authorization header to the Backend, it would be published to the throttle event

File: enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/api/ResponseObject.java [hunk 7]
```diff
@@ -34,6 +34,9 @@
     private ArrayList<String> removeHeaderMap = new ArrayList<>();
     private Map<String, String> metaDataMap;
     private boolean isDirectResponse = false;
+    private ArrayList<String> queryParamsToRemove = new ArrayList<>();
+    private Map<String, String> queryParamMap;
```
[the remark this answers is not in the document]
Comment (praminda) [reply enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/api/ResponseObject.java:38]: @VirajSalaka please fix this one too

**Review by praminda — APPROVED** [review]

**Comment by praminda** [comment]
Please fix the partial variable renaming. then we are good to merge.

File: enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/api/RestAPI.java [hunk 8]
```diff
@@ -288,4 +286,43 @@ private void loadCustomFilters(APIConfig apiConfig) {
...
+    private void populateRemoveAndProtectedHeaders(RequestContext requestContext) {
+        Map<String, SecuritySchemaConfig> securitySchemeDefinitions =
+                requestContext.getMatchedAPI().getSecuritySchemeDefinitions();
+        // API key headers are considered to be protected headers, such that the header would not be sent
+        // to backend and traffic manager.
+        // This would prevent leaking credentials, even if user is invoking unsecured resource with some
+        // credentials.
+        for (Map.Entry<String, SecuritySchemaConfig> entry : securitySchemeDefinitions.entrySet()) {
+            SecuritySchemaConfig schema = entry.getValue();
+            if ("apiKey".equalsIgnoreCase(schema.getType())) {
```
Comment (AmaliMatharaarachchi) [inline enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/api/RestAPI.java:299]:
```suggestion
            if (APIConstants.SWAGGER_API_KEY_AUTH_TYPE_NAME.equalsIgnoreCase(schema.getType())) {
```

File: enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/api/RestAPI.java [hunk 9]
```diff
@@ -288,4 +286,43 @@ private void loadCustomFilters(APIConfig apiConfig) {
...
+                if ("header".equals(schema.getIn())) {
```
Comment (AmaliMatharaarachchi) [inline enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/api/RestAPI.java:300]:
```suggestion
                if (APIConstants.SWAGGER_API_KEY_IN_HEADER.equals(schema.getIn())) {
```

File: enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/api/RestAPI.java [hunk 10]
```diff
@@ -288,4 +286,43 @@ private void loadCustomFilters(APIConfig apiConfig) {
...
+                    requestContext.getProtectedHeaders().add(schema.getName());
+                    requestContext.getRemoveHeaders().add(schema.getName());
+                    continue;
+                }
+                if ("query".equals(schema.getIn())) {
```
Comment (AmaliMatharaarachchi) [inline enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/api/RestAPI.java:305]:
```suggestion
                if (APIConstants.SWAGGER_API_KEY_IN_QUERY.equals(schema.getIn())) {
```

File: enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/security/jwt/APIKeyAuthenticator.java (hunk 1 above)
Comment (VirajSalaka) [reply enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/security/jwt/APIKeyAuthenticator.java]: fixed with https://github.com/wso2/product-microgateway/pull/2563/commits/9ca6828292e1cc968c8af8031e58816a1b85a49a

File: enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/security/jwt/InternalAPIKeyAuthenticator.java (hunk 2 above)
Comment (VirajSalaka) [reply enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/security/jwt/InternalAPIKeyAuthenticator.java]: fixed with https://github.com/wso2/product-microgateway/pull/2563/commits/9ca6828292e1cc968c8af8031e58816a1b85a49a

**Comment by choreo-cicd** [comment]
[failed] dev-deployment : 20211215.32

**Comment by choreo-cicd** [comment]
[succeeded] dev-deployment : 20211215.43
