### PR TITLE
bug-fix: subscription throttling does not work for self contained access token

### LINKED ISSUE #2368: Subscription Throttling does not work with self contained tokens.
### Description:

If a self contained access token is used, subscription throttling does not work. The reason is that `stopOnQuotaReach` is not populated properly within the authentication context. [1]

[1] https://github.com/wso2/product-microgateway/blob/7036ca8118a69bd8fda04b8d31e31545ee8bc0fe/enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/throttle/ThrottleFilter.java#L190

### Steps to reproduce:
Use choreo-connect-with-apim with throttling enabled.
Login to API Manager admin portal and change the value under bronze subscription throttle policy (<10)
Create an API in API Manager
Use the jwt the token:
```
eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsIng1dCI6Ik16WXhNbUZrT0dZd01XSTBaV05tTkRjeE5HWXdZbU00WlRBM01XSTJOREF6WkdRek5HTTBaR1JsTmpKa09ERmtaRFJpT1RGa01XRmhNelUyWkdWbE5nIn0.eyJhdWQiOiJodHRwOlwvXC9vcmcud3NvMi5hcGltZ3RcL2dhdGV3YXkiLCJzdWIiOiJhZG1pbkBjYXJib24uc3VwZXIiLCJhcHBsaWNhdGlvbiI6eyJvd25lciI6ImFkbWluIiwidGllclF1b3RhVHlwZSI6InJlcXVlc3RDb3VudCIsInRpZXIiOiIxMFBlck1pbiIsIm5hbWUiOiJEZWZhdWx0QXBwbGljYXRpb24iLCJpZCI6MywidXVpZCI6bnVsbH0sInNjb3BlIjoiYW1fYXBwbGljYXRpb25fc2NvcGUgZGVmYXVsdCIsImlzcyI6Imh0dHBzOlwvXC9sb2NhbGhvc3Q6OTQ0M1wvb2F1dGgyXC90b2tlbiIsInRpZXJJbmZvIjp7IkJyb256ZSI6eyJ0aWVyUXVvdGFUeXBlIjoicmVxdWVzdENvdW50Iiwic3RvcE9uUXVvdGFSZWFjaCI6dHJ1ZSwic3Bpa2VBcnJlc3RMaW1pdCI6MCwic3Bpa2VBcnJlc3RVbml0IjpudWxsfX0sImtleXR5cGUiOiJQUk9EVUNUSU9OIiwic3Vic2NyaWJlZEFQSXMiOlt7InN1YnNjcmliZXJUZW5hbnREb21haW4iOiJjYXJib24uc3VwZXIiLCJuYW1lIjoiUGl6emFTaGFja0FQSSIsImNvbnRleHQiOiJcL3Bpenphc2hhY2tcLzEuMC4wIiwicHVibGlzaGVyIjoiYWRtaW4iLCJ2ZXJzaW9uIjoiMS4wLjAiLCJzdWJzY3JpcHRpb25UaWVyIjoiQnJvbnplIn1dLCJjb25zdW1lcktleSI6InVJamZRM3lkVWFteUtXZEZlS192NVhzTG1VRWEiLCJleHAiOjE2NzE4MjAyNDYsImlhdCI6MTYzNTgyMDI0NiwianRpIjoiYmNkYmFkM2EtZGRmZi00MjBkLWIyMWUtNmZlMmE2ZGI2Zjk5In0.HKXZaPbUjenYB4D6S4BmrcuqXfPzL-EqRg16UQNJu46XS88YcygA1JDqzAGjsqvk-ZRkt1-3NlH8y928vL8lqlJSN6B1n6lcKz1fkQQsvlNuI9x2rRx8JULgIlCWZ06HKtHTARyHkDv9nFFgSGXoz0jAWiGpbzqClehycKloKzklUEFex2beIZakZ6DWmh0ZLIHFwVdG37vkJ0LCEju-BeFNwAWcd7S5UzsoRys6AAukDXWf8S3vn9nBCwtgKuZo_uuVM0YCxNIv94kwVcWG79rF3F4zRPiQr29MFGfGWZy-TN2c97R_Y5HFAWupej0czWOeVzakb330j5mYKMM-vA
```

### Environment details (with versions):
- OS:
- Client:
- Env (Docker/K8s):

---

### PR DESCRIPTION
**Pull request by VirajSalaka**
### Purpose

StopOnQuotaReach is properly populated as that was the root cause for subscription throttling failure.

### Issues

Fixes #2368

### Automation tests
 - Unit tests added: No
 - Integration tests added: Yes

### Tested environments

Not Tested

---
#### Maintainers: Check before merge
- [x] Assigned 'Type' label
- [x] Assigned the project
- [x] Validated respective github issues
- [x] Assigned milestone to the github issue(s)

### CODE REVIEW

File: enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/security/jwt/JWTAuthenticator.java [hunk 1]
```diff
@@ -435,6 +435,15 @@ private JSONObject validateSubscriptionFromClaim(String name, String version, JW
...
                         validationInfo.setTier(subTier);
+                        if (payload.getClaim(APIConstants.JwtTokenConstants.TIER_INFO) != null) {
+                            JSONObject tierInfo = (JSONObject) payload.getClaim(
+                                    APIConstants.JwtTokenConstants.TIER_INFO);
+                            if (tierInfo.get(subTier) != null) {
+                                JSONObject subTierInfo = (JSONObject) tierInfo.get(subTier);
+                                validationInfo.setStopOnQuotaReach((Boolean)
+                                        subTierInfo.get(APIConstants.JwtTokenConstants.STOP_ON_QUOTA_REACH));
+                            }
+                        }
```
Comment (suksw) [inline enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/security/jwt/JWTAuthenticator.java:446]: Shall we call this as a method defined in KeyValidator?

Comment (VirajSalaka) [reply enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/security/jwt/JWTAuthenticator.java:446]: It is only used by this method right?

Comment (suksw) [reply enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/security/jwt/JWTAuthenticator.java:446]: Yes, thought it would be useful for the API key path as well. Had to use a different flow there anyway. We can keep this as it is.

**Review by pubudu538 — APPROVED** [review]

**Review by suksw — APPROVED** [review]

**Comment by choreo-cicd** [comment]
[failed] dev-deployment : 20211215.32

**Comment by choreo-cicd** [comment]
[succeeded] dev-deployment : 20211215.43
