### PR TITLE
Deploy to default env when env not specified

### LINKED ISSUE #2522: Can't deploy exported Pizzashack API apictl
### Description:

When newly created Pizzashack API in apim is exported and deployed to CC using apictl, it doesn't get deployed. There is no log in the adapter log except following.
```java
adapter_1   | 2021-12-04 05:24:26 INFO [auth.go:156] - [auth.ValidateToken] [-] Valid token recieved
```
### Steps to reproduce:
1. Start standalone CC deployement
2. Start APIM separately
3. Deploy sample pizzashack API in API Manager
4. Export pizzashack API using apictl `apictl export api -n PizzaShackAPI -v 1.0.0 -e dev`
5. Deploy above exported API to cc `apictl mg deploy api -f PizzaShackAPI_1.0.0.zip -e dev -k`
6. Try to invoke the API. You'll notice its not deployed.
### Affected Product Version:

1.0.0-beta2-snapshot
### Environment details (with versions):
- OS: linux
- Client: apict
- Env (Docker/K8s): docker

### PR DESCRIPTION
**Pull request by praminda**
### Purpose

There can be api projects which doesn't specify the env to deploy the API. We deploy these APIs to default env.
### Issues

Fixes #2522

### Automation tests
 - Unit tests added: No
 - Integration tests added: No

### Tested environments

docker-compose

---
#### Maintainers: Check before merge
- [x] Assigned 'Type' label
- [x] Assigned the project
- [x] Validated respective github issues
- [x] Assigned milestone to the github issue(s)

### CODE REVIEW

File: adapter/internal/api/apis_impl.go [hunk 1]
```diff
@@ -173,13 +173,31 @@ func validateAndUpdateXds(apiProject mgw.ProjectAPI, override *bool) (err error)
...
 		overrideValue = false
 	} else {
 		overrideValue = *override
 	}
+
+	// when deployment-environments is missing in the API Project, definition we deploy to default
+	// environment
+	if apiProject.Deployments == nil {
+		conf, _ := config.ReadConfigs()
+		for _, mapping := range conf.Adapter.VhostMapping {
```
Comment (renuka-fernando) [inline adapter/internal/api/apis_impl.go:187]: We should only deploy to the default environment
default env from https://github.com/wso2/product-microgateway/blob/ccf0d7f6b0531a1b625d16266a7e655e24190500/adapter/config/parser.go#L44
default vhost from https://github.com/wso2/product-microgateway/blob/ccf0d7f6b0531a1b625d16266a7e655e24190500/adapter/config/parser.go#L104

**Review by pubudu538 — APPROVED** [review]

**Review by pubudu538 — APPROVED** [review]

**Review by renuka-fernando — APPROVED** [review]

**Comment by choreo-cicd** [comment]
[failed] dev-deployment : 20211215.32

**Comment by choreo-cicd** [comment]
[succeeded] dev-deployment : 20211215.43
