### PR TITLE
[envoy-gw] Refactor update API

### LINKED ISSUE #1621: [envoy-gw] Multiple APIs in the same name can be created
### Description:
Since there are multiple API maps (swagger2, swagger3, websocket) used to store API definitions, multiple APIs in the same name can be created.

### Steps to reproduce:
Deploy 3 swagger2, swagger3, websocket type projects with the same name and the version.

---

### PR DESCRIPTION
**Pull request by SuKSW**
### Purpose
1. Fixes #1621 - Replace multiple API maps (swagger2, swagger3, websocket) with one API map (existing mgwSwagger)
2. Rename vendorExtensible to vendorExtensions
3. Update apiMapKey to vhost:name:version

### Automation tests
 - Unit tests updated: Yes
 - Integration tests added: No

---
#### Maintainers: Check before merge
- [x] Assigned 'Type' label
- [x] Assigned the project
- [x] Validated respective github issues
- [x] Assigned milestone to the github issue(s)

### CODE REVIEW

File: adapter/pkg/xds/xds_server.go [hunk 1]
```diff
@@ -198,76 +191,34 @@ func GetEnforcerApplicationKeyMappingCache() cachev3.SnapshotCache {
 func UpdateAPI(byteArr []byte, upstreamCerts []byte, apiType string, environments []string) {
 	var apiMapKey string
 	var newLabels []string
+	var mgwSwagger mgw.MgwSwagger
+	vhost := "default" //TODO: update once vhost feature added
```
Comment (VirajSalaka) [inline adapter/pkg/xds/xds_server.go:195]: Follow the pattern
// TODO: (<github-username>) task

**Review by VirajSalaka — APPROVED** [review]
