### PR TITLE
Bug fix : APIList Discovery Client cannot retrieve events 

### LINKED ISSUE #1591: Retrieve Subscription information from adapter to enforcer
### Describe your problem(s)
Subscription details of newly added/updated/deleted Subscription information and the Subscription information available at the startup need to be fetched from the control plane to the adapter. This information should be pushed to the enforcer in order to validate requests coming from the router.

### Describe your solution
Implement an xDS similar to the ApiDS

### How will you implement it

---

### PR DESCRIPTION
**Pull request by VirajSalaka**
### Purpose
$subject. This is due to the naming convention of the type URL included within the go-control-plane.

### Issues

Fixes #1591 (additional fixes on top of https://github.com/wso2/product-microgateway/pull/1625)

### Automation tests
 - Unit tests added: No
 - Integration tests added: No

### Tested environments

Not Tested

---
#### Maintainers: Check before merge
- [ ] Assigned 'Type' label
- [ ] Assigned the project
- [ ] Validated respective github issues
- [ ] Assigned milestone to the github issue(s)

### CODE REVIEW

File: adapter/pkg/subscription/subscription.go [hunk 1]
```diff
@@ -41,36 +41,42 @@ const (
...
-	subPolicyList     *resourceTypes.SubscriptionPolicyList
-	resources         = []resource{
+	// SubList contains the Subscription list
+	SubList           *resourceTypes.SubscriptionList
+	// AppList contains the Application list
+	AppList           *resourceTypes.ApplicationList
+	// AppKeyMappingList contains the Application key mapping list
+	AppKeyMappingList *resourceTypes.ApplicationKeyMappingList
+	// APIList contains the Api list
+	APIList *resourceTypes.APIList
```
Comment (praminda) [inline adapter/pkg/subscription/subscription.go:51]:
```suggestion
	APIList           *resourceTypes.APIList
```

**Review by praminda — APPROVED** [review]
