### PR TITLE
Fixes issues when used with tenants

### LINKED ISSUE #1889: JWT authentication failure for tenant APIs
### Description:
The following error happens when control plane is connected using tenant credentials.

### Steps to reproduce:
1. Add tenant domain as control plane credentials in `config.toml`
2. Create a API under that tenant in APIM and invoke
3. Following error occurs
```org.wso2.choreo.connect.enforcer.exception.EnforcerException: Key Algorithm not supported
	at org.wso2.choreo.connect.enforcer.security.jwt.validator.JWTValidator.validateSignature(JWTValidator.java:136) ~[org.wso2.choreo.connect.enforcer-0.9.0-beta-SNAPSHOT.jar:0.9.0-beta-SNAPSHOT]
	at org.wso2.choreo.connect.enforcer.security.jwt.validator.JWTValidator.validateToken(JWTValidator.java:87) ~[org.wso2.choreo.connect.enforcer-0.9.0-beta-SNAPSHOT.jar:0.9.0-beta-SNAPSHOT]
	at org.wso2.choreo.connect.enforcer.security.jwt.validator.JWTValidator.validateJWTToken(JWTValidator.java:75) ~[org.wso2.choreo.connect.enforcer-0.9.0-beta-SNAPSHOT.jar:0.9.0-beta-SNAPSHOT]
	at org.wso2.choreo.connect.enforcer.security.jwt.JWTAuthenticator.getJwtValidationInfo(JWTAuthenticator.java:521) [org.wso2.choreo.connect.enforcer-0.9.0-beta-SNAPSHOT.jar:0.9.0-beta-SNAPSHOT]
	at org.wso2.choreo.connect.enforcer.security.jwt.JWTAuthenticator.authenticate(JWTAuthenticator.java:127) [org.wso2.choreo.connect.enforcer-0.9.0-beta-SNAPSHOT.jar:0.9.0-beta-SNAPSHOT]
	at org.wso2.choreo.connect.enforcer.security.AuthFilter.authenticate(AuthFilter.java:123) [org.wso2.choreo.connect.enforcer-0.9.0-beta-SNAPSHOT.jar:0.9.0-beta-SNAPSHOT]
	at org.wso2.choreo.connect.enforcer.security.AuthFilter.handleRequest(AuthFilter.java:105) [org.wso2.choreo.connect.enforcer-0.9.0-beta-SNAPSHOT.jar:0.9.0-beta-SNAPSHOT]
	at org.wso2.choreo.connect.enforcer.api.API.executeFilterChain(API.java:41) [org.wso2.choreo.connect.enforcer-0.9.0-beta-SNAPSHOT.jar:0.9.0-beta-SNAPSHOT]
	at org.wso2.choreo.connect.enforcer.api.RestAPI.process(RestAPI.java:97) [org.wso2.choreo.connect.enforcer-0.9.0-beta-SNAPSHOT.jar:0.9.0-beta-SNAPSHOT]
	at org.wso2.choreo.connect.enforcer.server.RequestHandler.process(RequestHandler.java:60) [org.wso2.choreo.connect.enforcer-0.9.0-beta-SNAPSHOT.jar:0.9.0-beta-SNAPSHOT]
	at org.wso2.choreo.connect.enforcer.grpc.ExtAuthService.check(ExtAuthService.java:50) [org.wso2.choreo.connect.enforcer-0.9.0-beta-SNAPSHOT.jar:0.9.0-beta-SNAPSHOT]
	at io.envoyproxy.envoy.service.auth.v3.AuthorizationGrpc$MethodHandlers.invoke(AuthorizationGrpc.java:245) [org.wso2.choreo.connect.enforcer-0.9.0-beta-SNAPSHOT.jar:0.9.0-beta-SNAPSHOT]
	at io.grpc.stub.ServerCalls$UnaryServerCallHandler$UnaryServerCallListener.onHalfClose(ServerCalls.java:180) [org.wso2.choreo.connect.enforcer-0.9.0-beta-SNAPSHOT.jar:0.9.0-beta-SNAPSHOT]
	at io.grpc.internal.ServerCallImpl$ServerStreamListenerImpl.halfClosed(ServerCallImpl.java:331) [org.wso2.choreo.connect.enforcer-0.9.0-beta-SNAPSHOT.jar:0.9.0-beta-SNAPSHOT]
	at io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$1HalfClosed.runInContext(ServerImpl.java:814) [org.wso2.choreo.connect.enforcer-0.9.0-beta-SNAPSHOT.jar:0.9.0-beta-SNAPSHOT]
	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37) [org.wso2.choreo.connect.enforcer-0.9.0-beta-SNAPSHOT.jar:0.9.0-beta-SNAPSHOT]
	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123) [org.wso2.choreo.connect.enforcer-0.9.0-beta-SNAPSHOT.jar:0.9.0-beta-SNAPSHOT]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:?]
	at java.lang.Thread.run(Unknown Source) [?:?]
```

*The fix should come from both APIM and Choreo Connect*
This will not work with APIM 4.0.0-beta
Reason for the issue is when adapter pull key managers of the tenant, it returns the key manager of the super tenant due to bug(https://github.com/wso2/product-apim/issues/10927) in APIM.

### Environment details (with versions):
- OS:
- Client:
- Env (Docker/K8s):

---

### LINKED ISSUE #1890: Application level throttling does not work for tenant
### Description:
The issue is due to the wrong application throttle key. The throttle key is combination of `<APP_ID>:<Authenticated_User>`
But the authenticated username is getting resolved without the tenant domain. Hence throttling does not happens properly at the TM side.

### Environment details (with versions):
- OS:
- Client:
- Env (Docker/K8s):

---

### LINKED ISSUE #1891: Newly created subscription policies are not received by the Enforcer
### Description:
When new subscription policy is created from the APIM admin portal, that event is received by the adapter.
But adapter does not send it to enforcer via the jms connection. This is due to subscription event type name was wong at the adapter side. The APIM side event comes with name `SUBSCRIPTION`, but adapter filter out with name `SUBSCRIPTIONS`

### Environment details (with versions):
- OS:
- Client:
- Env (Docker/K8s):

---

### PR DESCRIPTION
**Pull request by Rajith90**
### Purpose
Fixes issues found when used with tenant.

### Issues

Fixes #1889 
Fixes #1890 
Fixes #1891 

### Automation tests
 - Unit tests added: Yes/No
 - Integration tests added: Yes/No

### Tested environments

Not Tested

---
#### Maintainers: Check before merge
- [x] Assigned 'Type' label
- [x] Assigned the project
- [x] Validated respective github issues
- [x] Assigned milestone to the github issue(s)

### CODE REVIEW

File: enforcer/src/main/java/org/wso2/choreo/connect/enforcer/discovery/ApplicationPolicyDiscoveryClient.java [hunk 1]
```diff
@@ -74,13 +79,33 @@
...
 
+    private void initConnection() {
+        if (GRPCUtils.isReInitRequired(channel)) {
+            if (channel != null && !channel.isShutdown()) {
+                channel.shutdownNow();
+                do {
+                    try {
+                        channel.awaitTermination(100, TimeUnit.MILLISECONDS);
+                    } catch (InterruptedException e) {
+                        logger.error("API list discovery channel shutdown wait was interrupted", e);
```
Comment (praminda) [inline enforcer/src/main/java/org/wso2/choreo/connect/enforcer/discovery/ApplicationPolicyDiscoveryClient.java:98]:
```suggestion
                        logger.error("Application policy discovery channel shutdown wait was interrupted", e);
```

File: enforcer/src/main/java/org/wso2/choreo/connect/enforcer/discovery/SubscriptionPolicyDiscoveryClient.java [hunk 2]
```diff
@@ -74,13 +79,33 @@
...
 
+    private void initConnection() {
+        if (GRPCUtils.isReInitRequired(channel)) {
+            if (channel != null && !channel.isShutdown()) {
+                channel.shutdownNow();
+                do {
+                    try {
+                        channel.awaitTermination(100, TimeUnit.MILLISECONDS);
+                    } catch (InterruptedException e) {
+                        logger.error("API list discovery channel shutdown wait was interrupted", e);
```
Comment (praminda) [inline enforcer/src/main/java/org/wso2/choreo/connect/enforcer/discovery/SubscriptionPolicyDiscoveryClient.java:98]:
```suggestion
                        logger.error("Subscription policy discovery channel shutdown wait was interrupted", e);
```

File: enforcer/src/main/java/org/wso2/choreo/connect/enforcer/discovery/scheduler/XdsSchedulerManager.java [hunk 3]
```diff
@@ -188,4 +190,32 @@ public synchronized void stopConfigDiscoveryScheduling() {
...
+    public synchronized void stopApplicationPolicyDiscoveryScheduling() {
+        if (applicationPolicyDiscoveryScheduledFuture != null && !applicationPolicyDiscoveryScheduledFuture.isDone()) {
+            applicationPolicyDiscoveryScheduledFuture.cancel(false);
+        }
+    }
+
+    public synchronized void startSubscriptionPolicyDiscoveryScheduling() {
+        if (subscriptionPolicyDiscoveryScheduledFuture == null || subscriptionPolicyDiscoveryScheduledFuture.isDone()) {
+            subscriptionPolicyDiscoveryScheduledFuture = discoveryClientScheduler
+                    .scheduleWithFixedDelay(ConfigDiscoveryClient.getInstance(), 1, retryPeriod, TimeUnit.SECONDS);
```
Comment (praminda) [inline enforcer/src/main/java/org/wso2/choreo/connect/enforcer/discovery/scheduler/XdsSchedulerManager.java:211]:
```suggestion
                    .scheduleWithFixedDelay(SubscriptionPolicyDiscoveryClient.getInstance(), 1, retryPeriod, TimeUnit.SECONDS);
```

File: enforcer/src/main/java/org/wso2/choreo/connect/enforcer/discovery/scheduler/XdsSchedulerManager.java [hunk 4]
```diff
@@ -188,4 +190,32 @@ public synchronized void stopConfigDiscoveryScheduling() {
             configDiscoveryScheduledFuture.cancel(false);
         }
     }
+
+    public synchronized void startApplicationPolicyDiscoveryScheduling() {
+        if (applicationPolicyDiscoveryScheduledFuture == null || applicationPolicyDiscoveryScheduledFuture.isDone()) {
+            applicationPolicyDiscoveryScheduledFuture = discoveryClientScheduler
+                    .scheduleWithFixedDelay(ConfigDiscoveryClient.getInstance(), 1, retryPeriod,
```
Comment (praminda) [inline enforcer/src/main/java/org/wso2/choreo/connect/enforcer/discovery/scheduler/XdsSchedulerManager.java:197]:
```suggestion
                    .scheduleWithFixedDelay(ApplicationPolicyDiscoveryClient.getInstance(), 1, retryPeriod,
```

File: enforcer/src/main/java/org/wso2/choreo/connect/enforcer/util/FilterUtils.java [hunk 5]
```diff
@@ -444,7 +444,7 @@ public static void setThrottleErrorToContext(RequestContext context, int errorCo
      * @return tenant domain appended username
      */
     public static String buildUsernameWithTenant(String username, String tenantDomain) {
-        if (tenantDomain == null) {
+        if (tenantDomain == null || tenantDomain.isEmpty()) {
```
Comment (praminda) [inline enforcer/src/main/java/org/wso2/choreo/connect/enforcer/util/FilterUtils.java:447]:
```suggestion
        if (StringUtils.isEmpty(tenantDomain)) {
```

File: enforcer/src/main/java/org/wso2/choreo/connect/enforcer/util/FilterUtils.java [hunk 6]
```diff
@@ -488,4 +488,17 @@ public static String getClientIp(Map<String, String> headers, String knownIp) {
...
         return clientIp;
     }
+
+    /**
+     * Get the subscriber tenant domain from the subscriber user name.
+     *
+     * @param subscriber The name of the subscriber.
+     * @return tenant domain of the subscriber.
+     */
+    public static String getSubscriberTenantDomain(String subscriber, String apiTenantDomain) {
```
Comment (praminda) [inline enforcer/src/main/java/org/wso2/choreo/connect/enforcer/util/FilterUtils.java:498]: Is this method in use?

**Review by praminda — APPROVED** [review]

**Review by praminda — COMMENTED** [review]
Updating the review state

**Review by praminda — CHANGES_REQUESTED** [review]
.

**Review by praminda — APPROVED** [review]
