### PR TITLE
Fix #827 - NPE when open API used without wso2 extensions

### LINKED ISSUE #827: MGW created from open API with out wso2 extension give NPE
### Description:
Microgateway at least need x-wso2-basPath and x-wso2-production-endpoints or x-wso2-sandbox-endpoints vendor specific extension in the swagger file. 
We need to  provide proper error to the user

### Steps to reproduce:
Add the https://petstore.swagger.io/v2/swagger.json to the project and build the project
### OS and other environment details and versions:
- OS:
- Client:
- Env (Docker/K8s):

---

### PR DESCRIPTION
**Pull request by Rajith90**
### Purpose
This fixes the NPE when standard openAPI is used. This will give the error message to the user to inform to add minimum extensions to the swagger.

### Issues

Fixes #827

### Automation tests
 - Unit tests added: Yes/No
 - Integration tests added: Yes/No

### Tested environments

Not Tested

---
#### Maintainers: Check before merge
- [x] Assigned 'Type' label
- [x] Assigned the project
- [x] Validated respective github issues
- [x] Assigned milestone to the github issue(s)

### CODE REVIEW

File: components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/cmd/BuildCmd.java [hunk 1]
```diff
@@ -80,23 +80,33 @@ public void execute() {
...
-        if (!projectLocation.exists()) {
-            throw new CLIRuntimeException("Project " + projectName + " does not exist.");
-        }
-        //extract the ballerina platform and runtime
-        ToolkitLibExtractionUtils.extractPlatformAndRuntime();
+            if (!projectLocation.exists()) {
+                throw new CLIRuntimeException("Project " + projectName + " does not exist.");
+            }
+            // Some times user might run the command from different directory other than the directory where the project
+            // exists. In those cases we need to ask the users to
```
Comment (praminda) [inline components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/cmd/BuildCmd.java]:
```suggestion
            // exists. In those cases we need to ask the users to run the command in directory where project directory exists
```

File: components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/cmd/BuildCmd.java [hunk 2]
```diff
@@ -80,23 +80,33 @@ public void execute() {
...
+        try {
+            String projectCanonicalPath = projectLocation.getCanonicalPath();
+            String projectAbsolutePath = projectLocation.getAbsolutePath();
 
-        if (!projectLocation.exists()) {
-            throw new CLIRuntimeException("Project " + projectName + " does not exist.");
-        }
-        //extract the ballerina platform and runtime
-        ToolkitLibExtractionUtils.extractPlatformAndRuntime();
+            if (!projectLocation.exists()) {
```
Comment (praminda) [inline components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/cmd/BuildCmd.java]: In windows powershell if you type **pet** and hit `tab` to autocomplete **petstore** directory, autocompleted directory name will endup as **.\petstore** in that case this will complain project doesn't exists.

Comment (praminda) [reply components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/cmd/BuildCmd.java]: lets fix this later after a discussion
