### PR TITLE
Bug Fixes: Revision Undeployment is not working.

### LINKED ISSUE #1798: [envoy-gw] When undeploy a revision, it does not reflect in the router.
### Description:

Say you have deployed a revision of an API using API manager. Once you undeploy that revision, the router configs related to that particular API should be removed from envoy config.
But at the moment, even though the revision is undeployed, the router configs are present in envoy config.
### Steps to reproduce:
1. Create an API using API manager.
2. Deployed a revision to the envoy gw deployment.
3. Go to router config_dump( http://localhost:9000/config_dump)
4. You can see API resources are present.
5. Undeploy the revision from API manager.
6. Still the resources are present in config_dump.

### Environment details (with versions):
- OS: Ubuntu
- Client:
- Env (Docker/K8s): Docker

---

### PR DESCRIPTION
**Pull request by VirajSalaka**
### Purpose
Bug fixes:
Revision Undeploy operation not working.
Random number generator used for xds Version generator is not seeded properly.

### Issues

Fixes #1798 

### Automation tests
 - Unit tests added: No
 - Integration tests added: No

### Tested environments

Choreo-connect-with-apim setup

---
#### Maintainers: Check before merge
- [x] Assigned 'Type' label
- [x] Assigned the project
- [x] Validated respective github issues
- [x] Assigned milestone to the github issue(s)

### CODE REVIEW

File: adapter/internal/discovery/xds/server.go [hunk 1]
```diff
@@ -295,6 +297,38 @@ func DeleteAPI(vhost, apiName, version string) error {
...
+		labelMatched := false
+		for _, undeployedEnv := range undeployedEnvs {
+			if undeployedEnv == existingEnv {
+				labelMatched = true
+				break
+			}
+		}
+		if !labelMatched {
+			newLabels = append(newLabels, existingEnv)
+		}
```
Comment (renuka-fernando) [inline adapter/internal/discovery/xds/server.go:320]: We can use the existing function `arrayContains` here, and add to slice if not exists

**Review by renuka-fernando — APPROVED** [review]

**Review by Rajith90 — APPROVED** [review]
