### PR TITLE
Complete the Subscription Validation Flow

### LINKED ISSUE #1650: Subscription Validation
### Describe your problem(s)
When an API is created and published from the devportal, and some application subscribes to it, the tokens generated from that application's Keys should be allowed to access the API. Other requests should fail.

API/Application/Subscription creation/deletion/update operations may happen during the microgateway running or prior to the startup. Regardless of the time it occurred, the microgateway should respond correctly based on subscription.

Subscriptions can be temporary blocked from the API Publisher.

### How will you implement it

---

### PR DESCRIPTION
**Pull request by VirajSalaka**
### Purpose
This PR completes the subscription validation flow.

Additionally,
Support Upstream SNI.

### Remarks
If the event is dropped from AMQP connection between event hub and adapter, No recovery option is available.
If a separate version is deployed within the gateway, routes are not properly created.

Per each API Deploy event, a REST call would be triggered to pick the APIID as it is not included within event.

The API DTOs used for subscription validation and for other enforcer functionalities are different. 

### Issues

Fixes #1650

### Automation tests
 - Unit tests added: No
 - Integration tests added: No

### Tested environments

Mac OS Mojave

---
#### Maintainers: Check before merge
- [x] Assigned 'Type' label
- [x] Assigned the project
- [x] Validated respective github issues
- [x] Assigned milestone to the github issue(s)

### CODE REVIEW

File: adapter/pkg/subscription/subscription.go [hunk 1]
```diff
@@ -191,22 +225,55 @@ func invokeService(endpoint string, responseType interface{}, c chan response, r
...
 	if resp.StatusCode == http.StatusOK {
 		if err != nil {
-			c <- response{err, nil, endpoint, responseType}
+			c <- response{err, nil, endpoint, gatewayLabel, responseType}
 			logger.LoggerSubscription.Errorf("Error occurred while reading the response received for: "+serviceURL, err)
 			return
 		}
-		c <- response{nil, responseBytes, endpoint, responseType}
-
+		logger.LoggerSubscription.Debug("the request to the control plane over the REST API: " + serviceURL + " is successful.")
```
Comment (praminda) [inline adapter/pkg/subscription/subscription.go:240]:
```suggestion
		logger.LoggerSubscription.Debug("Request to the control plane over the REST API: " + serviceURL + " is successful.")
```

File: adapter/pkg/subscription/subscription.go [hunk 2]
```diff
@@ -191,22 +225,55 @@ func invokeService(endpoint string, responseType interface{}, c chan response, r
...
+func retrieveAPIListFromChannel(c chan response) {
+	for response := range c {
+		responseType := reflect.TypeOf(response.Type).Elem()
+		newResponse := reflect.New(responseType).Interface()
+
+		if response.Error == nil && response.Payload != nil {
+			err := json.Unmarshal(response.Payload, &newResponse)
+
+			if err != nil {
+				logger.LoggerSubscription.Errorf("Error occurred while unmarshalling the APIList response received for: "+response.Endpoint, err)
```
Comment (praminda) [inline adapter/pkg/subscription/subscription.go:257]:
```suggestion
				logger.LoggerSubscription.Errorf("Error occurred while unmarshalling the APIList response received for: " + response.Endpoint, err)
```

File: adapter/pkg/subscription/subscription.go [hunk 3]
```diff
@@ -191,22 +225,55 @@ func invokeService(endpoint string, responseType interface{}, c chan response, r
...
+			} else {
+				switch t := newResponse.(type) {
+				case *resourceTypes.APIList:
+					logger.LoggerSubscription.Debug("Received API List information.")
```
Comment (praminda) [inline adapter/pkg/subscription/subscription.go:261]: should we print some debug details of the list received. just to identify whats received and whats not

File: enforcer/src/main/java/org/wso2/micro/gateway/enforcer/config/EnvVarConfig.java [hunk 4]
```diff
@@ -34,10 +34,10 @@
     public static final String XDS_MAX_MSG_SIZE = "XDS_MAX_MSG_SIZE";
 
     // Since the container is running in linux container, path separator is not needed.
-    private static final String DEFAULT_TRUSTED_CA_CERTS_PATH = "/home/wso2/security";
+    private static final String DEFAULT_TRUSTED_CA_CERTS_PATH = "/home/wso2/security/truststore";
     private static final String DEFAULT_ADAPTER_HOST_NAME = "adapter";
     private static final String DEFAULT_ENFORCER_PRIVATE_KEY_PATH = "/home/wso2/security/keystore/mg.key";
-    private static final String DEFAULT_ENFORCER_PUBLIC_CERT_PATH = "/home/wso2/security/truststore/mg.pem";
+    private static final String DEFAULT_ENFORCER_PUBLIC_CERT_PATH = "/home/wso2/security/keystore/mg.pem";
```
Comment (praminda) [inline enforcer/src/main/java/org/wso2/micro/gateway/enforcer/config/EnvVarConfig.java:40]: same change is there in shalki's PR too. there will be a conflict

File: enforcer/src/main/java/org/wso2/micro/gateway/enforcer/subscription/SubscriptionDataStoreImpl.java [hunk 5]
```diff
@@ -313,13 +312,6 @@ public void addOrUpdateAPI(API api) {
 
     @Override
     public void addOrUpdateAPIWithUrlTemplates(API api) {
```
Comment (praminda) [inline enforcer/src/main/java/org/wso2/micro/gateway/enforcer/subscription/SubscriptionDataStoreImpl.java:314]: do we need these methods in the interface?

File: adapter/pkg/subscription/subscription.go (hunk 2 above)
Comment (VirajSalaka) [reply adapter/pkg/subscription/subscription.go:257]: VSCode plugin however removes the space between when I save.

File: enforcer/src/main/java/org/wso2/micro/gateway/enforcer/config/EnvVarConfig.java (hunk 4 above)
Comment (VirajSalaka) [reply enforcer/src/main/java/org/wso2/micro/gateway/enforcer/config/EnvVarConfig.java:40]: If I revert this, still it would create a conflict. I think best way is to keep it as it is. Since it is the exact change in both PRs it would not create a conflict.

File: enforcer/src/main/java/org/wso2/micro/gateway/enforcer/subscription/SubscriptionDataStoreImpl.java (hunk 5 above)
Comment (VirajSalaka) [reply enforcer/src/main/java/org/wso2/micro/gateway/enforcer/subscription/SubscriptionDataStoreImpl.java:314]: This is the exact interface used in API Manager. Hence we maintain the same but keep the body as unimplemented.

File: adapter/pkg/subscription/subscription.go (hunk 3 above)
Comment (VirajSalaka) [reply adapter/pkg/subscription/subscription.go]: fixed via https://github.com/wso2/product-microgateway/pull/1651/commits/f18b3f3c2667fea087e84767bdc3e0407ae1bbb0

File: adapter/pkg/subscription/subscription.go (hunk 1 above)
Comment (VirajSalaka) [reply adapter/pkg/subscription/subscription.go]: fixed via https://github.com/wso2/product-microgateway/pull/1651/commits/f18b3f3c2667fea087e84767bdc3e0407ae1bbb0

File: adapter/pkg/subscription/subscription.go [hunk 6]
```diff
@@ -38,22 +38,30 @@ const (
...
-	SubList           *resourceTypes.SubscriptionList
+	SubList *resourceTypes.SubscriptionList
 	// AppList contains the Application list
-	AppList           *resourceTypes.ApplicationList
+	AppList *resourceTypes.ApplicationList
 	// AppKeyMappingList contains the Application key mapping list
 	AppKeyMappingList *resourceTypes.ApplicationKeyMappingList
 	// APIList contains the Api list
-	APIList           *resourceTypes.APIList
+	APIList map[string]*resourceTypes.APIList
```
[the remark this answers is not in the document]
Comment (VirajSalaka) [reply adapter/pkg/subscription/subscription.go]: fixed via https://github.com/wso2/product-microgateway/pull/1651/commits/f18b3f3c2667fea087e84767bdc3e0407ae1bbb0

File: adapter/pkg/messaging/eventtypes.go [hunk 7]
```diff
@@ -77,6 +77,9 @@ type APIEvent struct {
 	APIStatus     string   `json:"apiStatus"`
 	APIType       string   `json:"apiType"`
 	Event
+	// TODO: (VirajSalaka) Remove this when the event is fixed from APIM side
+	Version string `json:"version"`
+	Context string `json:"context"`
```
Comment (VirajSalaka) [inline adapter/pkg/messaging/eventtypes.go:82]: Create an issue in APIM side as well

File: adapter/pkg/messaging/notificationListener.go [hunk 8]
```diff
@@ -44,14 +44,24 @@ const (
...
 // var variables
 var (
-	APIList                  = make([]resourceTypes.API, 0)
-	ScopeList                = make([]resourceTypes.Scope, 0)
-	APIListTimeStamp         = make(map[string]int64, 0)
-	ApplicationListTimeStamp = make(map[string]int64, 0)
+	ScopeList                         = make([]resourceTypes.Scope, 0)
+	apiListTimeStampMap               = make(map[string]int64, 0)
+	subsriptionsListTimeStampMap      = make(map[string]int64, 0)
+	ApplicationKeyMappingTimeStampMap = make(map[string]int64, 0)
```
Comment (VirajSalaka) [inline adapter/pkg/messaging/notificationListener.go:63]: Lowercase variable names

File: adapter/pkg/messaging/notificationListener.go [hunk 9]
```diff
@@ -44,14 +44,24 @@ const (
...
 
 // var variables
 var (
-	APIList                  = make([]resourceTypes.API, 0)
-	ScopeList                = make([]resourceTypes.Scope, 0)
-	APIListTimeStamp         = make(map[string]int64, 0)
-	ApplicationListTimeStamp = make(map[string]int64, 0)
+	ScopeList                         = make([]resourceTypes.Scope, 0)
+	apiListTimeStampMap               = make(map[string]int64, 0)
+	subsriptionsListTimeStampMap      = make(map[string]int64, 0)
```
Comment (VirajSalaka) [inline adapter/pkg/messaging/notificationListener.go:62]: Comment the reason behind keeping the timestamp map

File: adapter/pkg/messaging/notificationListener.go [hunk 10]
```diff
@@ -90,71 +100,69 @@ func handleNotification(deliveries <-chan amqp.Delivery, done chan error) {
...
-
-			if apiEvent.Event.Type == "API_CREATE" {
-				subscription.APIList.List = append(subscription.APIList.List, api)
-			} else if apiEvent.Event.Type == "API_UPDATE" {
-				subscription.APIList.List = removeAPI(subscription.APIList.List, apiEvent.APIID)
-				subscription.APIList.List = append(subscription.APIList.List, api)
-			} else if apiEvent.Event.Type == "API_DELETE" {
-				subscription.APIList.List = removeAPI(subscription.APIList.List, apiEvent.APIID)
+	// TODO: (VirajSalaka) Handle API Blocked event
+	if len(apiEvent.GatewayLabels) > 0 {
```
Comment (VirajSalaka) [inline adapter/pkg/messaging/notificationListener.go:114]: remove the if condition as it is handled by the for loop itself.

File: adapter/pkg/messaging/notificationListener.go [hunk 11]
```diff
@@ -90,71 +100,69 @@ func handleNotification(deliveries <-chan amqp.Delivery, done chan error) {
...
+									logger.LoggerMsg.Debugf("APIList for apiIId: %s is not updated as it already exists", apiEvent.UUID)
+									return
+								}
+							}
+							queryParamMap := make(map[string]string, 3)
+							queryParamMap[subscription.GatewayLabelParam] = configuredEnv
+							queryParamMap[subscription.ContextParam] = apiEvent.Context
+							queryParamMap[subscription.VersionParam] = apiEvent.Version
+							// TODO: (VirajSalaka) Fix the REST API call once the APIM Event hub implementation is fixed.
+							go subscription.InvokeService(subscription.ApisEndpoint, subscription.APIListMap[env], queryParamMap,
```
Comment (VirajSalaka) [inline adapter/pkg/messaging/notificationListener.go:139]: Use a single label and do the REST API call, since for each request, the same response is recieved.

File: adapter/pkg/messaging/notificationListener.go [hunk 12]
```diff
@@ -212,6 +232,7 @@ func handleSubscriptionEvents(data []byte, eventType string) {
 
 // handleScopeRelatedEvents to process scope related events
 func handleScopeEvents(data []byte, eventType string) {
+	// TODO: (VirajSalaka) Decide the usage
```
Comment (VirajSalaka) [inline adapter/pkg/messaging/notificationListener.go:235]: Remove as it is unused.

File: adapter/pkg/messaging/notificationListener.go [hunk 13]
```diff
@@ -261,69 +284,104 @@ func handlePolicyEvents(data []byte, eventType string) {
...
+	return applications[:len(applications)-1]
 }
 
 func removeSubscription(subscriptions []resourceTypes.Subscription, id int32) []resourceTypes.Subscription {
-	index := 0
-	for _, i := range subscriptions {
-		if i.SubscriptionID != id {
-			subscriptions[index] = i
-			index++
+	deleteIndex := -1
```
Comment (VirajSalaka) [inline adapter/pkg/messaging/notificationListener.go:316]: Add a log

File: adapter/pkg/messaging/notificationListener.go [hunk 14]
```diff
@@ -261,69 +284,104 @@ func handlePolicyEvents(data []byte, eventType string) {
...
 	}
 }
 
 func removeApplication(applications []resourceTypes.Application, id int32) []resourceTypes.Application {
-	index := 0
-	for _, i := range applications {
-		if i.ID != id {
-			applications[index] = i
-			index++
+	deleteIndex := -1
```
Comment (VirajSalaka) [inline adapter/pkg/messaging/notificationListener.go:300]: `TODO: (VirajSalaka) Improve the search logic with binary search mechanism`

File: adapter/pkg/subscription/subscription.go [hunk 15]
```diff
@@ -79,33 +84,54 @@ var (
...
 	var responseChannel = make(chan response)
 	for _, url := range resources {
-		go invokeService(url.endpoint, url.responseType, responseChannel, 0)
+		go InvokeService(url.endpoint, url.responseType, nil, responseChannel, 0)
+	}
+
+	// Take the configured labels from the adapter
+	configuredEnvs := conf.ControlPlane.EventHub.EnvironmentLabels
+
+	if len(configuredEnvs) > 0 {
```
Comment (VirajSalaka) [inline adapter/pkg/subscription/subscription.go:124]: If condition can be removed

File: adapter/pkg/subscription/subscription.go [hunk 16]
```diff
@@ -79,33 +84,54 @@ var (
...
+		for _, configuredEnv := range configuredEnvs {
+			queryParamMap := make(map[string]string, 1)
+			queryParamMap[GatewayLabelParam] = configuredEnv
```
Comment (VirajSalaka) [inline adapter/pkg/subscription/subscription.go:127]: Use default variable when the gatewayLabel is not provided.

File: adapter/pkg/subscription/subscription.go [hunk 17]
```diff
@@ -191,22 +226,59 @@ func invokeService(endpoint string, responseType interface{}, c chan response, r
...
+							logger.LoggerSubscription.Debugf("Received API List information for API : %s", api.UUID)
+						}
+					}
+					if _, ok := APIListMap[response.GatewayLabel]; !ok {
+						// During the startup
+						APIListMap[response.GatewayLabel] = newResponse.(*resourceTypes.APIList)
+					} else {
+						// API Details retrieved after startup contains single API per response.
+						if len(apiListResponse.List) == 1 {
+							APIListMap[response.GatewayLabel].List = append(APIListMap[response.GatewayLabel].List, apiListResponse.List[0])
```
Comment (VirajSalaka) [inline adapter/pkg/subscription/subscription.go:274]: too much length

File: adapter/pkg/messaging/eventtypes.go (hunk 7 above)
Comment (VirajSalaka) [reply adapter/pkg/messaging/eventtypes.go:82]: https://github.com/wso2/product-apim/issues/9991

File: adapter/pkg/messaging/notificationListener.go (hunk 8 above)
Comment (VirajSalaka) [reply adapter/pkg/messaging/notificationListener.go]: fixed via https://github.com/wso2/product-microgateway/pull/1651/commits/34135e565e0feb892396850af240c35fdc8c4499

File: adapter/pkg/messaging/notificationListener.go (hunk 9 above)
Comment (VirajSalaka) [reply adapter/pkg/messaging/notificationListener.go:64]: fixed via https://github.com/wso2/product-microgateway/pull/1651/commits/34135e565e0feb892396850af240c35fdc8c4499

File: adapter/pkg/messaging/notificationListener.go (hunk 11 above)
Comment (VirajSalaka) [reply adapter/pkg/messaging/notificationListener.go]: https://github.com/wso2/product-apim/issues/9993

If we make this change, it wont be necessary to call the service again at all. Hence the suggestion is not applied.

File: adapter/pkg/messaging/notificationListener.go (hunk 12 above)
Comment (VirajSalaka) [reply adapter/pkg/messaging/notificationListener.go]: fixed via https://github.com/wso2/product-microgateway/pull/1651/commits/34135e565e0feb892396850af240c35fdc8c4499

File: adapter/pkg/messaging/notificationListener.go (hunk 13 above)
Comment (VirajSalaka) [reply adapter/pkg/messaging/notificationListener.go:327]: added via https://github.com/wso2/product-microgateway/pull/1651/commits/f5b9d8236247dd1f4b3a10c15d8fd7de35f403f8

File: adapter/pkg/subscription/subscription.go (hunk 15 above)
Comment (VirajSalaka) [reply adapter/pkg/subscription/subscription.go]: fixed via https://github.com/wso2/product-microgateway/pull/1651/commits/34135e565e0feb892396850af240c35fdc8c4499

File: adapter/pkg/messaging/notificationListener.go (hunk 10 above)
Comment (VirajSalaka) [reply adapter/pkg/messaging/notificationListener.go]: fixed via https://github.com/wso2/product-microgateway/pull/1651/commits/34135e565e0feb892396850af240c35fdc8c4499

File: adapter/pkg/subscription/subscription.go (hunk 17 above)
Comment (VirajSalaka) [reply adapter/pkg/subscription/subscription.go]: fixed via https://github.com/wso2/product-microgateway/pull/1651/commits/51d6b114b31ec3cfef0adc098bc7e925db2eaa6e

File: adapter/pkg/subscription/subscription.go (hunk 16 above)
Comment (VirajSalaka) [reply adapter/pkg/subscription/subscription.go]: fixed via https://github.com/wso2/product-microgateway/pull/1651/commits/34135e565e0feb892396850af240c35fdc8c4499

File: adapter/pkg/messaging/notificationListener.go (hunk 14 above)
Comment (Rajith90) [reply adapter/pkg/messaging/notificationListener.go:310]: Lets add the TODO in the code

**Review by Rajith90 — APPROVED** [review]

File: adapter/pkg/messaging/notificationListener.go (hunk 14 above)
Comment (VirajSalaka) [reply adapter/pkg/messaging/notificationListener.go:311]: added via https://github.com/wso2/product-microgateway/pull/1651/commits/39630098027060f89dcb70ec211525197f7b1f3f

**Review by praminda — APPROVED** [review]
