### PR TITLE
Fix project structure related issues

### LINKED ISSUE #714: [toolkit] Error when target folder is not in the project
### Description:
If we build a project that does not have a target folder, then it gives the error [1]

`org.wso2.apimgt.gateway.cli.exception.CLIInternalException: Error occurred while generating source code for the open API definitions.
	at org.wso2.apimgt.gateway.cli.cmd.BuildCmd.execute(BuildCmd.java:120)
	at java.util.Optional.ifPresent(Optional.java:159)
	at org.wso2.apimgt.gateway.cli.cmd.Main.main(Main.java:48)
Caused by: java.nio.file.NoSuchFileException: /var/jenkins_home/workspace/MicroGatewayPipeline/MGW-Projects/bookstore/target/gen
	at sun.nio.fs.UnixException.translateToIOException(UnixException.java:86)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
	at sun.nio.fs.UnixFileSystemProvider.createDirectory(UnixFileSystemProvider.java:384)
	at java.nio.file.Files.createDirectory(Files.java:674)
	at org.wso2.apimgt.gateway.cli.utils.GatewayCmdUtils.createGenDirectoryStructure(GatewayCmdUtils.java:906)
	at org.wso2.apimgt.gateway.cli.cmd.BuildCmd.execute(BuildCmd.java:105)
	... 2 more`

### Steps to reproduce:
1. Init a project
2. Add an open API
3. Build the project
4. Commit the project to the github and checkout to different location.
5. Then build the project from new location.

Since when checkout from github the target folder is missing. Hence the issue happens

### Affected Product Version:
3.0.1

### OS, DB, other environment details and versions:
- OS: ANy
- Client:
- DB:
- Env (Docker/K8s): ANy

---

### LINKED ISSUE #715: [toolkit] Error building when interceptor folder is missing
### Description:
Following error occurs when a project without interceptor folder is build.
`org.wso2.apimgt.gateway.cli.exception.CLIInternalException: Error occurred while generating source code for the open API definitions.
	at org.wso2.apimgt.gateway.cli.cmd.BuildCmd.execute(BuildCmd.java:120)
	at java.util.Optional.ifPresent(Optional.java:159)
	at org.wso2.apimgt.gateway.cli.cmd.Main.main(Main.java:48)
Caused by: java.nio.file.NoSuchFileException: /var/jenkins_home/workspace/MicroGatewayPipeline/MGW-Projects/bookstore/interceptors
	at sun.nio.fs.UnixException.translateToIOException(UnixException.java:86)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
	at sun.nio.fs.UnixCopyFile.copy(UnixCopyFile.java:526)
	at sun.nio.fs.UnixFileSystemProvider.copy(UnixFileSystemProvider.java:253)
	at java.nio.file.Files.copy(Files.java:1274)
	at org.wso2.apimgt.gateway.cli.utils.GatewayCmdUtils.copyFolder(GatewayCmdUtils.java:686)
	at org.wso2.apimgt.gateway.cli.utils.GatewayCmdUtils.copyAndReplaceFolder(GatewayCmdUtils.java:635)
	at org.wso2.apimgt.gateway.cli.cmd.BuildCmd.execute(BuildCmd.java:108)
	... 2 more
`

### Steps to reproduce:
This happens when we check out project from git hub any other VCS.Because interceptor folder is empty, those folder will not be committed. Hence upon checkout and building it gives the error

### Affected Product Version:
3.0.1

### OS, DB, other environment details and versions:
- OS:
- Client:
- DB:
- Env (Docker/K8s):

---
#### Related Issues:
https://github.com/wso2/product-microgateway/issues/714

### PR DESCRIPTION
**Pull request by praminda**
### Purpose

1. Creating target directory on initializing a project causes issues in CICD integration. Therefore target directory will be created at the build time of a project.
1. By default Interceptor directory of e mgw project is an empty directory. If such a project is committed into a VCS (git, svn, etc...) other devs building the same project will get build errors since empty directories doesn't get committed to VCS.

### Issues

Fixes #714 
FIxes #715 

### Automation tests
 - Unit tests added: No
 - Integration tests added: No

### Tested environments

- MacOS

---
#### Maintainers: Check before merge
- [x] Assigned 'Type' label
- [x] Assigned the project
- [x] Validated respective github issues
- [x] Assigned milestone to the github issue(s)

### CODE REVIEW

File: components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/utils/GatewayCmdUtils.java [hunk 1]
```diff
@@ -685,20 +679,58 @@ private static void copyFolder(File sourceFolder, File destinationFolder) throws
...
+     * @return created file
+     * @throws IOException Failed delete or create the file in {@code path}
+     */
+    public static File createFile(String path, String fileName, boolean overwrite) throws IOException {
+        String filePath = path + File.separator + fileName;
+        File file = new File(filePath);
+        if (overwrite && file.exists() && file.isFile()) {
+            boolean isDeleted = file.delete();
+            if (!isDeleted) {
+                throw new CLIInternalException("Failed to overwrite file: " + filePath);
```
Comment (Rajith90) [inline components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/utils/GatewayCmdUtils.java]: Isn't it better to log these messages. I think we log only the e.message in the main function

File: components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/utils/GatewayCmdUtils.java [hunk 2]
```diff
@@ -685,20 +679,58 @@ private static void copyFolder(File sourceFolder, File destinationFolder) throws
...
+            }
+        }
+
+        if (!file.exists() && !file.isFile()) {
+            boolean isCreated = file.createNewFile();
+            if (isCreated) {
+                logger.trace("File: {} created.", filePath);
+            } else {
+                throw new CLIInternalException("Failed to create file: " + filePath);
```
Comment (Rajith90) [inline components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/utils/GatewayCmdUtils.java]: Isn't it better to log these messages. I think we log only the e.message in the main function
