### PR TITLE
Bug fix: [ Websocket] APIs with no endpointBasepath results in XDS update failure

### LINKED ISSUE #2445: [Websocket] XDS update fails when websocket API endpoint basepath is empty.
### Description:
When the websocket API's endpointBasepath (a basePath appended to the end of endpoint's hostname and port) is empty, the xds update fails. 

```
router_1    | [2021-11-19 09:25:03.291][1][warning][config] [source/common/config/grpc_subscription_impl.cc:126] gRPC config for type.googleapis.com/envoy.config.route.v3.RouteConfiguration rejected: Proto constraint validation failed (RouteConfigurationValidationError.VirtualHosts[0]: embedded message failed validation | caused by VirtualHostValidationError.Routes[3]: embedded message failed validation | caused by RouteValidationError.Decorator: embedded message failed validation | caused by DecoratorValidationError.Operation: value length must be at least 1 characters): name: "default"
```

### Steps to reproduce:

Open publisher portal and create a websocket API.

Assign an endpoint `ws://localhost:8080`.

And check the router/adapter logs.

### Affected Product Version:
choreo-connect-1.0.0-alpha

### Environment details (with versions):
- OS:
- Client:
- Env (Docker/K8s):

---

### PR DESCRIPTION
**Pull request by VirajSalaka**
### Purpose

The decorator field is used for tracing purposes. Hence rather than attaching resource path or endpoint basePath, it sounds correct to assign it with the complete routePath as routerPath remains unique across the router.
https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/route/v3/route_components.proto.html?highlight=decorator#envoy-v3-api-msg-config-route-v3-decorator

### Issues

Fixes #2445 

### Automation tests
 - Unit tests added: No
 - Integration tests added: No

### Tested environments

Not Tested

---
#### Maintainers: Check before merge
- [x] Assigned 'Type' label
- [x] Assigned the project
- [x] Validated respective github issues
- [x] Assigned milestone to the github issue(s)

### CODE REVIEW

File: adapter/internal/oasparser/envoyconf/routes_with_clusters.go [hunk 1]
```diff
@@ -647,13 +647,13 @@ func createRoute(params *routeCreateParams) *routev3.Route {
...
-	if apiType == model.WS {
-		decorator = &routev3.Decorator{
-			Operation: endpointBasepath,
-		}
-	} else if apiType == model.HTTP || apiType == model.WEBHOOK {
+	// route path could be empty only if there is no basePath for API or the endpoint available,
+	// and resourcePath is also an empty string.
+	// Empty check is added to run the gateway in failsafe mode, as if the decorator string is
+	// empty, the route configuration does not apply.
+	if strings.TrimSpace(routePath) != "" {
```
Comment (praminda) [inline adapter/internal/oasparser/envoyconf/routes_with_clusters.go:654]: if `ws://localhost:8080` is the endpoint. can routePath be empty?

Comment (VirajSalaka) [reply adapter/internal/oasparser/envoyconf/routes_with_clusters.go:654]: nope. Since the APIs hosted in gateway will have a context all the time.

**Review by praminda — APPROVED** [review]

**Review by pubudu538 — APPROVED** [review]

**Comment by choreo-cicd** [comment]
[succeeded] dev-deployment : 20211202.25
