### PR TITLE
[Analytics] Publish analytics events for blocked API calls.

### LINKED ISSUE #2701: Analytics Events for BlockedAPI Errors are not published.
### Description:
Events related to Blocked API Invocations are discarded from the enforcer at the moment. It is required to publish a fault event for that scenario as well.

### Affected Product Version:
1.0.0

### Environment details (with versions):
- OS:
- Client:
- Env (Docker/K8s):

---

### LINKED ISSUE #2791: Blocked API Life cycle state is not in effect when using Internal Keys
### Description:
$subject

### Steps to reproduce:
Create an API. 
Block it in the life cycle state.
Try invoking the API with Internal Key.

### Affected Product Version:
choreo-connect-1.0.0-alpha

### Environment details (with versions):
- OS:
- Client:
- Env (Docker/K8s):

---

### PR DESCRIPTION
**Pull request by VirajSalaka**
### Purpose

Following API Manager's implementation, the blocked API calls would be categorized under Auth failures despite the fact that the status code is 503.

### Issues

Fixes #2701 
Fixes #2791 

### Automation tests
 - Unit tests added: No
 - Integration tests added: Yes (for Internal key for blocked APIs test case_

### Tested environments

Not Tested

---
#### Maintainers: Check before merge
- [x] Assigned 'Type' label
- [x] Assigned the project
- [x] Validated respective github issues
- [x] Assigned milestone to the github issue(s)

### CODE REVIEW

File: enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/security/jwt/InternalAPIKeyAuthenticator.java [hunk 1]
```diff
@@ -203,8 +207,31 @@ public AuthenticationContext authenticate(RequestContext requestContext) throws
...
+                                        GeneralErrorCodeConstants.API_BLOCKED_CODE,
+                                        GeneralErrorCodeConstants.API_BLOCKED_MESSAGE);
+                            }
+                            log.debug("Internal Key Authentication is successful.");
+                        }
+                    } catch (APISecurityException e) {
+                        throw e;
                     } finally {
-                        log.debug("Internal Key authentication successful.");
+                        log.debug("Internal Key authentication complete.");
```
Comment (pubudu538) [inline enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/security/jwt/InternalAPIKeyAuthenticator.java:234]: Internal Key authentication complete. --> Internal Key Authentication is completed.

Comment (pubudu538) [reply enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/security/jwt/InternalAPIKeyAuthenticator.java:234]:
```suggestion
                        log.debug("Internal Key authentication is completed.");
```

File: integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/util/websocket/WsClient.java [hunk 2]
```diff
@@ -119,7 +119,7 @@ protected void initChannel(SocketChannel ch) throws SSLException {
             Channel ch = b.connect(uri.getHost(), uri.getPort()).sync().channel();
             handler.handshakeFuture().sync();
 
-            log.info("Websocket client handshake complete");
+            log.info("Websocket client handshake is complete");
```
Comment (pubudu538) [inline integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/util/websocket/WsClient.java:122]:
```suggestion
            log.info("Websocket client handshake is completed");
```

**Review by pubudu538 — APPROVED** [review]
