### PR TITLE
Fixes #469

### LINKED ISSUE #469: Micro-gw build/import commands cannot be executed directly on copied project.
**Description:**
Immediately after extracting microgateway toolkit, micro-gw build/import commands does not work if the project folder is copied from some other place.

**Steps to reproduce:**
Extract micro-gw toolkit and set the environmental variables.
Copy an existing project, which is working properly and paste in your working directory.
execute micro-gw build <project_name>

### PR DESCRIPTION
**Pull request by VirajSalaka**

### CODE REVIEW

File: components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/utils/ToolkitLibExtractionUtils.java [hunk 1]
```diff
@@ -0,0 +1,72 @@
...
+        } catch (IOException e) {
+            String message = "Error while unzipping platform and runtime while project setup";
+            LOGGER.error(message, e);
+            throw new CLIInternalException(message);
+        }
+    }
+
+    private static void extractBallerinaDist(String destination, String libPath, String baloPath, String breLibPath) throws IOException {
+        if (!Files.exists(Paths.get(destination))) {
+            ZipUtils.unzip(destination + GatewayCliConstants.EXTENSION_ZIP, destination, true);
```
Comment (Rajith90) [inline components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/utils/ToolkitLibExtractionUtils.java]: Passing the value true here will add same jar twice to the class path. accepth the isAddtoClasspath as a method variable and pass it to ZipUtils.unzip method

File: components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/utils/ToolkitLibExtractionUtils.java [hunk 2]
```diff
@@ -0,0 +1,72 @@
...
+            String runtimeExtractedPath = libPath + File.separator + GatewayCliConstants.CLI_RUNTIME;
+            String platformExtractedPath =
+                    GatewayCmdUtils.getCLILibPath() + File.separator + GatewayCliConstants.CLI_PLATFORM;
+
+            extractBallerinaDist(platformExtractedPath, libPath, baloPath, breLibPath);
+            extractBallerinaDist(runtimeExtractedPath, libPath, baloPath, breLibPath);
+
+        } catch (IOException e) {
+            String message = "Error while unzipping platform and runtime while project setup";
+            LOGGER.error(message, e);
```
Comment (hasuniea) [inline components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/utils/ToolkitLibExtractionUtils.java]: If you catch it and log it and rethrow it, then there's no way for the upstream code to know that you've already logged the exception, and so the same exception might get logged twice.

File: components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/utils/ToolkitLibExtractionUtils.java (hunk 1 above)
Comment (VirajSalaka) [reply components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/utils/ToolkitLibExtractionUtils.java]: fixed.

File: components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/utils/ToolkitLibExtractionUtils.java (hunk 2 above)
Comment (VirajSalaka) [reply components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/utils/ToolkitLibExtractionUtils.java]: Removed the logger message.

Comment (Rajith90) [reply components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/utils/ToolkitLibExtractionUtils.java]: Please check before whether upstream method logs it. Its better to log it twice rather than not logging it

Comment (VirajSalaka) [reply components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/utils/ToolkitLibExtractionUtils.java]: Whenever CLIInternalException or CLIRuntimeException is thrown, it is logged in the Main Class. So it would be better to remove that additional log message.

Comment (hasuniea) [reply components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/utils/ToolkitLibExtractionUtils.java]: I checked the code. Upstream(Main class) logs the error message.

**Comment by praminda** [comment]
Fixes #469
