### PR TITLE
Provide descriptive error message when an invalid URL is provided.

### LINKED ISSUE #963: Malformed URL error, when no sandbox endpoint is defined
### Description:
If the openAPI definition contains only the "x-wso2-production-endpoints", the following error message pops when the build command is executed.
`micro-gw: Malformed URL is provided: '/'.`

Although there is no sandbox-endpoint is defined, a sandbox endpoint object is created with the value "/". That is the reason for this behavior.

### Steps to reproduce:
This is the sample openAPI file used.

```yaml
openapi: 3.0.0
info:
  version: 1.0.0
  title: echo
x-wso2-basePath: /echo/1.0.0
x-wso2-production-endpoints:
  urls:
  - http://10.0.1.148:8688/
paths:
  /:
    post:
      summary: echos the request
      operationId: echoRequest
      responses:
        '200':
          description: Expected response to a valid request
```

### Affected Product Version:
3.1.0-M1

### Environment details (with versions):
- OS: Mac OS Mojave

---

### LINKED ISSUE #1044: Failed to build with OAPI v3 swagger JSON
### Description:
`micro-gw build <project_name>` fails when trying to build a project which is initiated by the default [petstore OAPI v3](http://petstore.swagger.io:8080/api/v3/openapi.json) swagger JSON with the error `Malformed URL is provided: '/api/v3'`

### Steps to reproduce:
1. `micro-gw init petstore -a http://petstore.swagger.io:8080/api/v3/openapi.json`
2. `micro-gw build petstore`

### Affected Product Version:
3.1.0-beta

### PR DESCRIPTION
**Pull request by VirajSalaka**
### Purpose
To provide a detailed error description, when a valid URL is not present as an endpoint. This will include details like API name, version, resource (if it is resource level) and reason. (Rather than just providing the error as Malformed URL)
In addition to that, the servers object will only be treated as a production endpoint. (Previously, it have been treated as a sandbox endpoint as well)

### Issues
Fixes #963
Fixes #1044 

### Automation tests
 - Unit tests added: No
 - Integration tests added: No

### Tested environments
OS: MacOS Mojave

---
#### Maintainers: Check before merge
- [x] Assigned 'Type' label
- [x] Assigned the project
- [x] Validated respective github issues
- [x] Assigned milestone to the github issue(s)

### CODE REVIEW

File: components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/model/template/service/BallerinaPath.java [hunk 1]
```diff
@@ -41,51 +42,87 @@ public BallerinaPath() {
...
             entry = new AbstractMap.SimpleEntry<>("options", operation);
             operations.add(entry);
         }
         if (item.getHead() != null) {
             setServersToOperationLevel(item.getHead(), item.getServers());
-            operation = new BallerinaOperation().buildContext(item.getHead(), api);
+            try {
+                operation = new BallerinaOperation().buildContext(item.getHead(), api);
+            } catch (CLICompileTimeException e) {
+                throw new CLICompileTimeException("Error while parsing the information under HEAD resource.\n\t-"
```
Comment (praminda) [inline components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/model/template/service/BallerinaPath.java]: Shouldn't we propagate e to the top? not only the message?

File: components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/cmd/BuildCmd.java [hunk 2]
```diff
@@ -124,7 +124,7 @@ public void execute() {
             }
             String toolkitConfigPath = CmdUtils.getMainConfigLocation();
             init(projectName, toolkitConfigPath, deploymentConfigPath);
-            outStream.print("Generating sources...");
+            outStream.print("Generating sources...\n");
```
[the remark this answers is not in the document]
Comment (VirajSalaka) [reply components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/cmd/BuildCmd.java]: Otherwise 
Generating sources...micro-gw: Error...

File: components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/model/template/service/BallerinaPath.java (hunk 1 above)
Comment (Rajith90) [reply components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/model/template/service/BallerinaPath.java]: Yes its better to propagate the stack trace to the top. So the stack trace will be in the log file instead of the console

File: components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/cmd/BuildCmd.java (hunk 2 above)
[the remark this answers is not in the document]
Comment (praminda) [reply components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/cmd/BuildCmd.java]: I have a fix in my mind. I'll try that later. For now lets merge with `\n`

File: components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/model/template/service/BallerinaPath.java (hunk 1 above)
Comment (VirajSalaka) [reply components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/model/template/service/BallerinaPath.java]: Yes. I will fix that.

Comment (VirajSalaka) [reply components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/model/template/service/BallerinaPath.java]: fixed via https://github.com/wso2/product-microgateway/pull/1072/commits/8b13b9b1338bc7afc348bf0799d3db5050254d2d

File: components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/model/mgwcodegen/MgwEndpointDTO.java [hunk 3]
```diff
@@ -55,37 +52,25 @@ public String getEndpointUrl() {
     }
 
     /**
-     * sets endpointUrl and isEtcdEnabled
+     * sets endpointUrl and isEtcdEnabled.
```
[the remark this answers is not in the document]
Comment (VirajSalaka) [reply components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/model/mgwcodegen/MgwEndpointDTO.java]: added via https://github.com/wso2/product-microgateway/pull/1072/commits/8b13b9b1338bc7afc348bf0799d3db5050254d2d
