### PR TITLE
[Bug-Fix] Unlimited API Level Tier is not applied after resource level tier applied for once

### LINKED ISSUE #2561: Unlimited API Tier does not apply after resource level tier is set once
### Description:

$subject

### Steps to reproduce:
1. Create an API and assign resource level Tier and save.
2. Deploy the API and see if the resource level tier is applied.
3. Then change it to API Level and assign unlimited tier. 
4. Deploy the API and see if the resource level tier is applied. (in this case, it would apply.)

### Environment details (with versions):
- OS:
- Client:
- Env (Docker/K8s):

---

### PR DESCRIPTION
**Pull request by VirajSalaka**
bug fix: If the openAPI's throttling is set to some operation level, and then revert back to API Level with Unlimited Tier, the resource level throttling still enforced instead on Unlimited Tier.

### Issues

Fixes #2561 

### Automation tests
 - Unit tests added: No
 - Integration tests added: No

### Tested environments

Not Tested

---
#### Maintainers: Check before merge
- [x] Assigned 'Type' label
- [x] Assigned the project
- [x] Validated respective github issues
- [x] Assigned milestone to the github issue(s)

### CODE REVIEW

File: enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/throttle/ThrottleFilter.java [hunk 1]
```diff
@@ -298,7 +298,9 @@ private Decision checkResourceThrottled(String throttleKey, String tier, Request
             tenantDomain = APIConstants.SUPER_TENANT_DOMAIN_NAME;
         }
 
-        if (!StringUtils.isEmpty(apiTier) && !ThrottleConstants.UNLIMITED_TIER.equals(apiTier)) {
+        // apiConfig instance will have the tier assigned only if openapi definition contains the
+        // extension
+        if (!StringUtils.isEmpty(api.getTier())) {
```
Comment (praminda) [inline enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/throttle/ThrottleFilter.java:303]: Do we need same fix around condition at L138?

**Review by praminda — COMMENTED** [review]
/

File: enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/throttle/ThrottleFilter.java (hunk 1 above)
Comment (VirajSalaka) [reply enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/throttle/ThrottleFilter.java:303]: Since it is unlimited tier, I guess it does not matter which throttle key we set. But, I think it is better to have the fix in L138 as well, since now the apiTier in APIConfig remains empty (with this fix)

Comment (VirajSalaka) [reply enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/throttle/ThrottleFilter.java:303]: fixed via https://github.com/wso2/product-microgateway/pull/2556/commits/4f7da1064b42b3726baf0a0b30544284a1159edd

Comment (praminda) [reply enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/throttle/ThrottleFilter.java:303]: One more thing. Do you think we need to change the logic in `getApiTier` method?

Comment (VirajSalaka) [reply enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/throttle/ThrottleFilter.java:303]: Nope. It is better to keep it in that way I guess. Because if the API Tier is not present, it means unlimited .

**Review by praminda — APPROVED** [review]

**Comment by choreo-cicd** [comment]
[failed] dev-deployment : 20211215.32

**Comment by choreo-cicd** [comment]
[succeeded] dev-deployment : 20211215.43
