### PR TITLE
Prevent building project without valid api definition

### LINKED ISSUE #552: A project can be built without an api definition.
**Description:**
API project can be built even without an api definition. 

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**
3.0.0-RC1

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**
- micro-gw init petstore-project
- micro-gw build petstore-project

**Related Issues:**

### PR DESCRIPTION
**Pull request by VirajSalaka**

### CODE REVIEW

**Comment by praminda** [comment]
Shall we change the PR title to something meaningful.
Ex:
Prevent building project without valid api definition

File: components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/cmd/BuildCmd.java [hunk 1]
```diff
@@ -93,10 +93,11 @@ public void execute() {
         //extract the ballerina platform and runtime
         ToolkitLibExtractionUtils.extractPlatformAndRuntime();
 
-        File importedAPIDefLocation = new File(GatewayCmdUtils.getProjectAPIDefinitionsDirectoryPath(projectName));
+        File importedAPIDefLocation = new File(GatewayCmdUtils.getProjectGenAPIDefinitionPath(projectName));
         File addedAPIDefLocation = new File(GatewayCmdUtils.getProjectAPIFilesDirectoryPath(projectName));
 
-        if (importedAPIDefLocation.list() != null && importedAPIDefLocation.list().length == 0
+        if (((importedAPIDefLocation.list() != null && importedAPIDefLocation.list().length == 0) ||
+                importedAPIDefLocation.list() == null)
```
Comment (praminda) [inline components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/cmd/BuildCmd.java]: Same logic should apply to `addedAPIDefLocation.list()` aswell
Also the logic in this if block looks too complex for one condition. Shall we break it down to two simple if blocks using `isValidImportedAPIDefLocation` and `isValidAddedAPIDefLocation` boolean variables

File: components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/cmd/BuildCmd.java [hunk 2]
```diff
@@ -117,6 +119,17 @@ public void execute() {
         }
     }
 
+    private boolean checkFolderContentAvailablity(String fileLocation) {
+        File file = new File(fileLocation);
+        FilenameFilter filter = (f, name) -> (name.endsWith(".yaml") || name.endsWith(".json"));
```
Comment (praminda) [inline components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/cmd/BuildCmd.java:124]: Shall we add yml to the list. also we'll need to add support for .yml loading during the actual build as we discussed recently.
