### PR TITLE
Fix 1176

### LINKED ISSUE #1176: Error when defining only resource level endpoints
### Description:
I am getting the following error when defined only the resource level endpoints using the extension x-wso2-production-endpoints. 

**Error:**
micro-gw: Error while parsing the openAPI defintion for the API "Online-Store-Api : v1.0.0".
	-The provided endpoint using the "servers" object is invalid.
	-Malformed Url is provided :/

**Swagger Def:**

```
openapi: 3.0.0
info:
  title: Online-Store-Api
  version: v1.0.0
  description: This API contains operations related to online shopping store.
x-wso2-basePath: /storemep/{version}
paths:
  /products:
    get:
      x-wso2-production-endpoints:
        urls:
          - http://products.micro
      responses:
        "200":
          description: ""

  /products/{productId}:
    get:
      parameters:
        - name: productId
          in: path
          required: true
          schema:
            type: string
      x-wso2-production-endpoints:
        urls:
          - http://products.micro
      responses:
        "200":
          description: ""
```

### Affected Product Version:
3.1.0

### Environment details (with versions):
- OS:
- Client:
- Env (Docker/K8s):

---

### PR DESCRIPTION
**Pull request by VirajSalaka**
### Purpose
Fix the microgateway project build failure, where all the resource endpoints are defined but no API Level endpoint is provided. 

### Issues

Fixes #1176 

### Automation tests
 - Unit tests added: No
 - Integration tests added: Yes

### Tested environments

MacOS Mojave

---
#### Maintainers: Check before merge
- [x] Assigned 'Type' label
- [x] Assigned the project
- [x] Validated respective github issues
- [x] Assigned milestone to the github issue(s)

### CODE REVIEW

File: components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/model/template/service/BallerinaOperation.java [hunk 1]
```diff
@@ -129,6 +129,13 @@ public BallerinaOperation buildContext(Operation operation, ExtendedAPI api) thr
         this.scope = OpenAPICodegenUtils.getMgwResourceScope(operation);
         //set resource level endpoint configuration
         setEpConfigDTO(operation);
+        //If production/sandbox endpoints for both API and Operation is not available, Error should be thrown.
+        if (api.getEndpointConfigRepresentation().getProdEndpointList() == null &&
+                api.getEndpointConfigRepresentation().getSandboxEndpointList() == null
+                && !hasProdEpConfig
+                && !hasSandEpConfig) {
+            throw new CLICompileTimeException("The endpoint Configuration is not provided for the operation.");
```
Comment (praminda) [inline components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/model/template/service/BallerinaOperation.java:137]: Better to mention which operation this is. Otherwise user have to go through all operations to find which operation is causing the issue.

Comment (VirajSalaka) [reply components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/model/template/service/BallerinaOperation.java:137]: This was implemented in such a way that the exception thrown in here is caught from the method above. Otherwise, we need to pass the operation name, path information to this layer. This is a sample error message.
```
micro-gw: Error while parsing information under path:/products/{productId}in the API "Online-Store-Api:v1.0.0".
        -Error while parsing the information under GET resource.
        -The endpoint Configuration is not provided for the operation.
```

Comment (praminda) [reply components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/model/template/service/BallerinaOperation.java:137]: Great
