### PR TITLE
Add deployment-Config Path with build command, Fix the issue with help command

### LINKED ISSUE #473: Error while executing "micro-gw help" command
**Description:**

When I execute micro-gw help command as soon as I set the PATH variable, the following error could be seen (even before executing **micro-gw help** ).

```
$ micro-gw help
Error: Could not find or load main class org.wso2.apimgt.gateway.cli.cmd.Main
```
Then after **micro-gw init**, I executed micro-gw help and micro-gw setup commands and I got the following error.

```
$ micro-gw help
[micro-gw: unknown help topic ``, Run 'micro-gw help' for usage.]

$ micro-gw help setup
[micro-gw: unknown help topic `setup`, Run 'micro-gw help' for usage.]

```

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**
3.0.0-alpha
**OS, DB, other environment details and versions:**    

**Steps to reproduce:**
Mentioned in the description.

**Related Issues:**

### LINKED ISSUE #474: Deployment config can not be passed as command line argument in build command
**Description:**
The depolyment-config.toml can not be passed as command line argument when building the project. It should ne always inside the conf folder of the project.
In earlier versions like 2.6.0, this can be passed in the setup command.

**Affected Product Version:**
3.0.0-alpha

### PR DESCRIPTION
**Pull request by VirajSalaka**
Fixes #474

### CODE REVIEW

File: components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/cmd/ImportCmd.java [hunk 1]
```diff
@@ -363,13 +365,20 @@ private static void init(String configPath, String projectName) {
                 logger.error("Configuration: {} Not found.", configPath);
                 throw new CLIInternalException("Error occurred while loading configurations.");
             }
-
+            if(deploymentConfig != null){
+                Path deploymentConfigFile = Paths.get(deploymentConfig);
+                if(Files.exists(deploymentConfigFile)){
```
Comment (chamindias) [inline components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/cmd/ImportCmd.java:370]: Small formatting issue...
