### PR TITLE
Fix #1239 #802 : Provide endpoint proxy, pool, retry, circuit breaker configs

### LINKED ISSUE #802: Micro gateway can not call services through a proxy
### Description:
If the back end service can be connected via n proxy server, then microgateway does not have a way to specify the proxy server url, port, username and password values.

### Steps to reproduce:
1. Expose backend service and make it connect via a proxy server(squid proxy)
### OS and other environment details and versions:
- OS:
- Client:
- Env (Docker/K8s):

---

### LINKED ISSUE #1239: Provide endpoint timeout, retry, circuit breaker and pool configurations
### Describe your problem(s)
In microgateway when connecting with upstream service endpoints at the moment we can not specify timeout periods, retries and circuit breaker configurations when specifying production endpoints in the open API definition

### Describe your solution
Allow the "x-wso2-production-endpoints" to be extend with the additional configurations required for advance configurations

### PR DESCRIPTION
**Pull request by Rajith90**
### Purpose

This PR add capability to define proxy configs, endpoint retries, circuit breakers when connecting with the backend endpoints

### Issues

Fixes #1239 
Fixes #802 

### Automation tests
 - Integration tests added: Yes

### Tested environments

Not Tested

---
#### Maintainers: Check before merge
- [x] Assigned 'Type' label
- [x] Assigned the project
- [x] Validated respective github issues
- [x] Assigned milestone to the github issue(s)

### CODE REVIEW

File: tests/src/test/java/org/wso2/micro/gateway/tests/common/MockBackEndServer.java [hunk 1]
```diff
@@ -326,6 +327,54 @@ public void configure(HttpsParameters params) {
...
+                    exchange.getResponseBody().write(response);
+                    exchange.close();
+                    retryDone = true;
+                }
+                byte[] response = ResponseConstants.responseBodyV1.getBytes();
+                exchange.getResponseHeaders().set(HttpHeaderNames.CONTENT_TYPE.toString(),
+                        TokenManagementConstants.CONTENT_TYPE_APPLICATION_JSON);
+                exchange.sendResponseHeaders(HttpURLConnection.HTTP_OK, response.length);
+                exchange.getResponseBody().write(response);
+                exchange.close();
```
Comment (Rajith90) [inline tests/src/test/java/org/wso2/micro/gateway/tests/common/MockBackEndServer.java:358]: Set the retryDone false

File: distribution/resources/conf/default-micro-gw.conf.template [hunk 2]
```diff
@@ -191,14 +191,36 @@
...
   # Hostname verification
   verifyHostname=true
+  # Skip validating certificates when ssl is used
+  disableSslVerification = false
+  # Enable http2 when connecting with upstream backend endpoints.
+  enableHttp2 = true
+  #Proxy configurations required when microgateway connects to an upstream back end via a corporate proxy.
+  [httpClients.proxy]
+    enable = false
+    enableInternalServices = false
```
Comment (Rajith90) [inline distribution/resources/conf/default-micro-gw.conf.template:209]: Describe these paramaters
