### PR TITLE
Corrected API count when deploying the APIs

### LINKED ISSUE #2776: Shows incorrect API count when deploying the APIs
### Description:
When deploying a single API, the following logs can be seen.

2022-03-23 12:35:01 INFO [notification_listener.go:83] - [messaging.handleNotification] [-] Event API_LIFECYCLE_CHANGE is received []
2022-03-23 12:35:02 INFO [apis_fetcher.go:177] - [synchronizer.FetchAPIsFromControlPlane] [-] Pushing data to router and enforcer []
2022-03-23 12:35:02 INFO [apis_fetcher.go:58] - [synchronizer.PushAPIProjects] [-] Start Deploying 2 API/s... []
2022-03-23 12:35:02 INFO [apis_fetcher.go:96] - [synchronizer.PushAPIProjects] [-] Start deploying api from file (API_ID:REVISION_ID).zip : ee083022-605f-4f37-aa38-0fbd62f183f5-81dfa1d1-3687-43a7-9d5e-6936876ddb5a.zip []
2022-03-23 12:35:02 INFO [apis_impl.go:277] - [api.ApplyAPIProjectFromAPIM] [-] Deploying api mok4:v in Organization carbon.super []
2022-03-23 12:35:02 INFO [server.go:382] - [xds.UpdateAPI] [-] Added/Updated the content for Organization : carbon.super under OpenAPI Key : localhost:ee083022-605f-4f37-aa38-0fbd62f183f5 []
2022-03-23 12:35:02 INFO [server.go:995] - [xds.UpdateEnforcerApis] [-] New API cache update for the label: Default version: 769787451 []
2022-03-23 12:35:02 INFO [server.go:940] - [xds.updateXdsCache] [-] New Router cache updated for the label: Default version: 865219964 []
2022-03-23 12:35:02 INFO [apis_fetcher.go:119] - [synchronizer.PushAPIProjects] [-] Successfully deployed 1 API/s []

### Steps to reproduce:

Tested with latest APIM pack.

### Environment details (with versions):
- OS:
- Client:
- Env (Docker/K8s):

---

### PR DESCRIPTION
**Pull request by Amila-Rukshan**
### Purpose

APIs count was read as files count minus one and there were two other meta data files called deployments.json and env_properties.json other than api files. Because of that it showed actual API count plus one in the log. APIs count was read using deployments descriptor to fix the issue. 

### Issues

Fixes #2776

### Automation tests
 - Unit tests added: No
 - Integration tests added: No

### Tested environments

OS: Linux
Env: Docker

---
#### Maintainers: Check before merge
- [x] Assigned 'Type' label
- [x] Assigned the project
- [x] Validated respective github issues
- [x] Assigned milestone to the github issue(s)

### CODE REVIEW

File: adapter/internal/synchronizer/apis_fetcher.go [hunk 1]
```diff
@@ -55,24 +55,27 @@ func PushAPIProjects(payload []byte, environments []string) error {
...
-	// apiFiles represents zipped API files fetched from API Manager
-	apiFiles := make(map[string]*zip.File, len(zipReader.File)-1)
 	// Read deployments from deployment.json file
 	deploymentDescriptor, envProps, err := sync.ReadRootFiles(zipReader)
 	if err != nil {
 		logger.LoggerSync.Error("Error occured while reading root files ", err)
 		return err
 	}
 
+	numberOfAPIDeployments := len(deploymentDescriptor.Data.Deployments)
```
Comment (pubudu538) [inline adapter/internal/synchronizer/apis_fetcher.go:66]: What is the content we get in the deployment descriptor? Can you paste the content here?

Also let's test the following flows.

1. With APIM and CC - API deployment and startup with APIs
2. CC only with apictl

Comment (Amila-Rukshan) [reply adapter/internal/synchronizer/apis_fetcher.go:66]: content of deployment descriptor looks like below when there are two apis 
image

Comment (Amila-Rukshan) [reply adapter/internal/synchronizer/apis_fetcher.go:66]: 1. CC only with apictl did not log API count information
image

2. With APIM and CC gives the API counts
when deploying 
image

when starting up with two APIs available
image

**Review by pubudu538 — APPROVED** [review]

**Review by renuka-fernando — APPROVED** [review]

**Review by pubudu538 — APPROVED** [review]
