### PR TITLE
[Bug-fix] Prioritize Swagger definition's vendor extensions over API.yaml for all APIs.

### LINKED ISSUE #1955: Prototyped APIs cannot be invoked
### Description:

state changes requires redeploying the API(create a new revision). simply only clicking prototype button does not work.

### Steps to reproduce:
(only tried in tenant user.)
create an API with a mocky.io endpoint as prototype backend. and publish as a prototype.
try to invoke the API.
API should be able to invoke w/o a token, but it shows the following error.

```
{"error_message":"Invalid Credentials","code":"900901","error_description":"Make sure you have provided the correct security credentials"}
```

### Environment details (with versions):
- OS:
- Client:
- Env (Docker/K8s):

---

### PR DESCRIPTION
**Pull request by VirajSalaka**
### Purpose

Via this PR, the API.yaml is processed at the earliest. Then the openapi definition is processed and if there are any changes compared to API.yaml (ex. endpoints) those will be overridden by the openAPI. 

So the priority would be,

API.yaml < servers/host property (properties from openapi spec) < x-wso2 extensions

But for the prototyped apis, the endpoints would be determined based on API.yaml (servers/host property is ignored). 

### Issues

Fixes #1955 

### Automation tests
 - Unit tests added: No
 - Integration tests added: Yes

### Tested environments

Not Tested

---
#### Maintainers: Check before merge
- [x] Assigned 'Type' label
- [x] Assigned the project
- [x] Validated respective github issues
- [x] Assigned milestone to the github issue(s)

### CODE REVIEW

File: adapter/internal/oasparser/model/mgw_swagger.go [hunk 1]
```diff
@@ -942,3 +946,118 @@ func (swagger *MgwSwagger) GetInterceptor(vendorExtensions map[string]interface{
...
+}
+
+//SetSwaggerFromAPIYaml populates the mgwSwagger object for APIs using API.yaml
+// TODO - (VirajSalaka) read cors config and populate mgwSwagger feild
+func (swagger *MgwSwagger) SetSwaggerFromAPIYaml(apiData APIYaml, apiType string) error {
+
+	data := apiData.Data
+	// UUID in the generated api.yaml file is considerd as swagger.id
+	swagger.id = data.ID
+	// Set apiType as WS for websockets
```
Comment (AmaliMatharaarachchi) [inline adapter/internal/oasparser/model/mgw_swagger.go:1004]:
```suggestion
```

File: adapter/internal/discovery/xds/server.go [hunk 2]
```diff
@@ -271,8 +271,13 @@ func UpdateAPI(vHost string, apiProject mgw.ProjectAPI, environments []string) (
 		apiEnvProps = apiEnvPropsV
 	}
 
+	mgwSwagger, err = operator.GetMgwSwaggerFromAPIYaml(apiProject.APIYaml, apiProject.APIType)
```
Comment (AmaliMatharaarachchi) [inline adapter/internal/discovery/xds/server.go:274]: line 284 getting security definitions from api.yaml, shouldn't it be applicable to both ws and rest apis? if so shall we move that also to this GetMgwSwaggerFromAPIYaml method

File: adapter/internal/oasparser/operator/operator.go [hunk 3]
```diff
@@ -145,11 +96,11 @@ func GetXWso2LabelsWebSocket(webSocketAPIDef model.MgwSwagger) []string {
 }
 
 /*
-GetMgwSwaggerWebSocket returns a MgwSwagger for the web socket APIs
+GetMgwSwaggerFromAPIYaml returns a MgwSwagger for the APIs using the API.Yaml file.
 */
-func GetMgwSwaggerWebSocket(apiData model.APIYaml) (model.MgwSwagger, error) {
+func GetMgwSwaggerFromAPIYaml(apiData model.APIYaml, apiType string) (model.MgwSwagger, error) {
```
Comment (AmaliMatharaarachchi) [inline adapter/internal/oasparser/operator/operator.go:101]: Shall we remove this method and directly call SetSwaggerFromAPIYaml from other places?

File: adapter/internal/discovery/xds/server.go (hunk 2 above)
Comment (VirajSalaka) [reply adapter/internal/discovery/xds/server.go:274]: API key option, X-wso2-auth-header options are not available for Websocket APIs. Hence, it would be okay to keep as it is I guess.

File: enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/security/AuthFilter.java [hunk 4]
```diff
@@ -181,7 +186,8 @@ private AuthenticationResponse authenticate(Authenticator authenticator, Request
      */
     private void updateClusterHeaderAndCheckEnv(RequestContext requestContext, AuthenticationContext authContext)
             throws APISecurityException {
-
+        log.info("Inside updateCluster env " + requestContext.getProdClusterHeader() + " " +
```
Comment (pubudu538) [inline enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/security/AuthFilter.java:189]: This Line gets printed for each and every request right? It is bad. let's make it a debug.

File: enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/security/AuthFilter.java [hunk 5]
```diff
@@ -193,12 +199,14 @@ private void updateClusterHeaderAndCheckEnv(RequestContext requestContext, Authe
                     requestContext.getProdClusterHeader());
             requestContext.getRemoveHeaders().remove(AdapterConstants.CLUSTER_HEADER);
             addRouterHttpHeaders(requestContext, APIConstants.API_KEY_TYPE_PRODUCTION);
+            log.info("Prod clusterheader is added. " + requestContext.getProdClusterHeader());
```
Comment (pubudu538) [inline enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/security/AuthFilter.java:202]: Same here.

File: enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/security/AuthFilter.java (hunk 4 above)
Comment (VirajSalaka) [reply enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/security/AuthFilter.java]: fixed

File: enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/security/AuthFilter.java (hunk 5 above)
Comment (VirajSalaka) [reply enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/security/AuthFilter.java]: fixed

**Review by pubudu538 — APPROVED** [review]

**Comment by choreo-cicd** [comment]
[failed] dev-deployment : 20211215.32

**Comment by choreo-cicd** [comment]
[succeeded] dev-deployment : 20211215.43
