### PR TITLE
Validate API name and version in definition.yaml. Fixes #443

### LINKED ISSUE #443: [dev-first] Error when matching swagger not found with definition.yaml
**Description:**
When we add a swagger to api_definitions folder and create the entry in the definitions.yaml , if the title and the versions for the API does not match with any of the swaggers then following error is logged.

`[2019-04-23 09:36:25,624] ERROR {org.wso2.apimgt.gateway.cli.cmd.Main} - Internal error occurred while executing command. 
java.lang.NullPointerException
	at org.wso2.apimgt.gateway.cli.utils.MgwDefinitionUtils.getProdEndpointList(MgwDefinitionUtils.java:57)
	at org.wso2.apimgt.gateway.cli.utils.OpenAPICodegenUtils.setAdditionalConfigsDevFirst(OpenAPICodegenUtils.java:300)
	at org.wso2.apimgt.gateway.cli.codegen.CodeGenerator.lambda$generate$1(CodeGenerator.java:134)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.Iterator.forEachRemaining(Iterator.java:116)
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
	at org.wso2.apimgt.gateway.cli.codegen.CodeGenerator.generate(CodeGenerator.java:129)
	at org.wso2.apimgt.gateway.cli.cmd.BuildCmd.execute(BuildCmd.java:111)
	at java.util.Optional.ifPresent(Optional.java:159)
	at org.wso2.apimgt.gateway.cli.cmd.Main.main(Main.java:51)` 

**Suggested Assignees:**
@VirajSalaka 

**Affected Product Version:**
3.0.0-alpha

**Steps to reproduce:**

1. Add the petstore swagger to api_definitions folder
2. Add and entry in the definitions.yaml without not matching title and version

### PR DESCRIPTION
**Pull request by VirajSalaka**

### CODE REVIEW

File: components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/cmd/BuildCmd.java [hunk 1]
```diff
@@ -109,6 +109,10 @@ public void execute() {
                 GatewayCmdUtils.copyFolder(GatewayCmdUtils.getProjectInterceptorsDirectoryPath(projectName),
                         GatewayCmdUtils.getProjectGenSrcInterceptorsDirectoryPath(projectName));
                 codeGenerator.generate(projectName, true);
+
+                //to indicate the api information which is not used in the code generation process, but included in
+                //definition.yaml
+                MgwDefinitionUtils.FindNotUsedAPIInformation(outStream);
```
Comment (Rajith90) [inline components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/cmd/BuildCmd.java]: No need to pass the outStream, lets directly use the System.out in FindNotUsedAPIInformation method. OutStream is also pointing to System.out

File: components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/utils/MgwDefinitionUtils.java [hunk 2]
```diff
@@ -117,4 +137,42 @@ private static boolean isResourceAvailable(String basePath, String path, String
...
+     * To find out the api information which is not used for code generation but included in the definitions.yaml
+     *
+     * @param outStream print stream if needed
+     */
+    public static void FindNotUsedAPIInformation(PrintStream outStream) {
+        rootDefinition.getApis().getApisMap().forEach((k, v) -> {
+            if (!v.getIsUsed()) {
+                String msg = "[Warning] API '" + v.getTitle() + "' version: '" + v.getVersion() + "' is not used but " +
+                        "added to the " + GatewayCliConstants.PROJECT_DEFINITION_FILE + ".";
+                LOGGER.info(msg);
```
Comment (Rajith90) [inline components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/utils/MgwDefinitionUtils.java]: Can't we use logger.warn here

Comment (VirajSalaka) [reply components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/utils/MgwDefinitionUtils.java]: We can, I will make the change.

File: components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/model/mgwdefinition/MgwAPIDefinition.java [hunk 3]
```diff
@@ -36,6 +36,8 @@
     private MgwPathsDefinition pathsDefinition;
     private String security; //todo: bring enum
     private APICorsConfigurationDTO corsConfiguration;
+    //to identify whether it has been used
+    private boolean isUsed = false;
```
Comment (praminda) [inline components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/model/mgwdefinition/MgwAPIDefinition.java]: If we rename like this we can remove the comment
```suggestion
    private boolean isDefinitionUsed = false;
```

File: components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/utils/MgwDefinitionUtils.java [hunk 4]
```diff
@@ -117,4 +137,42 @@ private static boolean isResourceAvailable(String basePath, String path, String
...
+                    LOGGER);
+        }
+    }
+
+    /**
+     * To find out the api information which is not used for code generation but included in the definitions.yaml
+     *
+     * @param outStream print stream if needed
+     */
+    public static void FindNotUsedAPIInformation(PrintStream outStream) {
```
Comment (praminda) [inline components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/utils/MgwDefinitionUtils.java]:
```suggestion
    public static void FindUnusedAPIInformation(PrintStream outStream) {
```

File: distribution/resources/bin/micro-gw [hunk 5]
```diff
@@ -248,32 +248,39 @@ if [ "$IS_BUILD_COMMAND" = true ] && [ "$CMD_PRO_NAME_VAL" != "" ] && [ "$MICRO_
...
-    MICRO_GW_LABEL_PROJECT_DIR="$MICRO_GW_PROJECT_DIR/$CMD_PRO_NAME_VAL"
-    pushd $MICRO_GW_LABEL_PROJECT_DIR/gen > /dev/null
-        # clean the content of target folder
-        if [ -d "$MICRO_GW_LABEL_PROJECT_DIR/target" ]; then
-            rm -rf $MICRO_GW_LABEL_PROJECT_DIR/target
-        fi
-        # build the ballerina source code for the label
-        ballerina build src/ -o $CMD_PRO_NAME_VAL.balx --offline --experimental --siddhiruntime
-    popd > /dev/null
+
```
Comment (praminda) [inline distribution/resources/bin/micro-gw]: Too many empty lines

File: components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/cmd/BuildCmd.java (hunk 1 above)
Comment (VirajSalaka) [reply components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/cmd/BuildCmd.java]: But in this way, it will have more flexibility to mention its own PrintStream. Shall we proceed in this way, or include System.out.

File: distribution/resources/bin/micro-gw [hunk 6]
```diff
@@ -248,32 +248,39 @@ if [ "$IS_BUILD_COMMAND" = true ] && [ "$CMD_PRO_NAME_VAL" != "" ] && [ "$MICRO_
...
+
+
+
+    if [ $? -eq 0 ]
```
Comment (praminda) [inline distribution/resources/bin/micro-gw]: @VirajSalaka Change for `.bat` file not here. You can check for ERRORLEVEL variable value `.bat` logic

File: components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/utils/MgwDefinitionUtils.java [hunk 7]
```diff
@@ -117,4 +137,42 @@ private static boolean isResourceAvailable(String basePath, String path, String
...
+        rootDefinition.getApis().getApisMap().forEach((k, v) -> {
+            if (!v.getIsUsed()) {
+                String msg = "[Warning] API '" + v.getTitle() + "' version: '" + v.getVersion() + "' is not used but " +
+                        "added to the " + GatewayCliConstants.PROJECT_DEFINITION_FILE + ".";
+                LOGGER.info(msg);
+                if(outStream != null){
+                    outStream.println(msg);
```
Comment (Rajith90) [inline components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/utils/MgwDefinitionUtils.java]: Do we need this message in the console output, shall we move this to a verbose kind of logs

Comment (VirajSalaka) [reply components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/utils/MgwDefinitionUtils.java]: added.

File: distribution/resources/bin/micro-gw (hunk 6 above)
Comment (VirajSalaka) [reply distribution/resources/bin/micro-gw]: added.

File: distribution/resources/bin/micro-gw (hunk 5 above)
Comment (VirajSalaka) [reply distribution/resources/bin/micro-gw]: removed.

File: components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/utils/MgwDefinitionUtils.java (hunk 2 above)
Comment (VirajSalaka) [reply components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/utils/MgwDefinitionUtils.java]: added.

File: components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/cmd/BuildCmd.java (hunk 1 above)
Comment (VirajSalaka) [reply components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/cmd/BuildCmd.java]: Implemented as suggested.

File: components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/utils/MgwDefinitionUtils.java [hunk 8]
```diff
@@ -117,4 +135,39 @@ private static boolean isResourceAvailable(String basePath, String path, String
...
+            //if the provided definitions.yaml file does not follow the yaml syntax
+        } catch (IOException e) {
+            throw GatewayCmdUtils.createValidationException("'definitions.yaml file cannot be parsed as yaml document.",
+                    LOGGER);
+        }
+    }
+
+    /**
+     * To find out the api information which is not used for code generation but included in the definitions.yaml
+     *
```
Comment (praminda) [inline components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/utils/MgwDefinitionUtils.java]:
```suggestion
```

File: components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/model/mgwdefinition/MgwAPIDefinition.java [hunk 9]
```diff
@@ -117,4 +119,22 @@ public String getResponseInterceptor() {
     public void setResponseInterceptor(String responseInterceptor) {
         this.responseInterceptor = responseInterceptor;
     }
+
+    /**
+     * Identify if the API information used or not
```
Comment (praminda) [inline components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/model/mgwdefinition/MgwAPIDefinition.java]: Can you add `.` at the end of first sentence in the javadoc description. Make sure this is followed in the whole diff.
```suggestion
     * Identify if the API information used or not.
```

File: components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/model/mgwdefinition/MgwAPIDefinition.java [hunk 10]
```diff
@@ -117,4 +119,22 @@ public String getResponseInterceptor() {
     public void setResponseInterceptor(String responseInterceptor) {
         this.responseInterceptor = responseInterceptor;
     }
+
+    /**
+     * Identify if the API information used or not.
+     *
+     * @return true if the API information is used inside
+     */
+    public boolean getIsUsed(){
```
Comment (mushthaq33) [inline components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/model/mgwdefinition/MgwAPIDefinition.java:128]: Formatting issue

File: components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/model/mgwdefinition/MgwAPIDefinition.java [hunk 11]
```diff
@@ -117,4 +119,22 @@ public String getResponseInterceptor() {
...
+        return isUsed;
+    }
+
+    /**
+     * Set the IsUsed if the API information is used
+     *
+     * @param flag true if the API information is used
+     */
+    public void setIsUsed(boolean flag){
```
Comment (mushthaq33) [inline components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/model/mgwdefinition/MgwAPIDefinition.java:137]: Formatting issue

File: components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/model/mgwdefinition/MgwAPIsDefinition.java [hunk 12]
```diff
@@ -35,13 +35,24 @@ public void setApis(String key, MgwAPIDefinition api) {
         apis.put(key, api);
     }
 
+    /**
+     * get all the api information from the root level
+     *
+     * @return map with (basepath, api information object)
+     */
+    public Map<String, MgwAPIDefinition> getApisMap(){
```
Comment (mushthaq33) [inline components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/model/mgwdefinition/MgwAPIsDefinition.java:43]: Formatting issue

File: components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/utils/GatewayCmdUtils.java [hunk 13]
```diff
@@ -142,6 +153,30 @@ public static CliLauncherException createUsageException(String errorMsg) {
...
     }
 
+    /**
+     * Create validation exception
+     * requires to set a system property to avoid ballerina compilation errors
+     *
+     * @param errorMsg Error message
+     * @return         CLIRuntimeException with the added error message
+     */
+    public static CLIRuntimeException createValidationException(String errorMsg, Logger logger){
```
Comment (mushthaq33) [inline components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/utils/GatewayCmdUtils.java:163]: Formatting issue

File: components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/utils/GatewayCmdUtils.java [hunk 14]
```diff
@@ -142,6 +153,30 @@ public static CliLauncherException createUsageException(String errorMsg) {
...
+    }
+
+    /**
+     * Create validation exception
+     * requires to set a system property to avoid ballerina compilation errors
+     *
+     * @param errorMsg Error message
+     * @return         CLIRuntimeException with the added error message
+     */
+    public static CLIRuntimeException createValidationException(String errorMsg, Exception e, Logger logger){
```
Comment (mushthaq33) [inline components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/utils/GatewayCmdUtils.java:175]: Formatting issue

File: components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/utils/GatewayCmdUtils.java [hunk 15]
```diff
@@ -1271,5 +1306,28 @@ public static String getProjectSwaggerFilePath(String projectName, String apiId)
...
 
+    /**
+     * To read the system variable VERBOSE_ENABLED
+     *
+     * @return true if verbose flag is enabled
+     */
+    private static Boolean setVerboseEnabled() {
+        String value = System.getProperty("VERBOSE_ENABLED");
+        //bat file provides T and shell script provides true
+        if (value.equals("T") || value.equalsIgnoreCase("true")) {
```
Comment (mushthaq33) [inline components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/utils/GatewayCmdUtils.java:1328]: Can we swap the equals to "T".equals(value) to avoid NPEs?

File: components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/model/mgwdefinition/MgwAPIDefinition.java (hunk 10 above)
Comment (VirajSalaka) [reply components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/model/mgwdefinition/MgwAPIDefinition.java:128]: the commented code is no longer available.

File: components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/model/mgwdefinition/MgwAPIDefinition.java (hunk 11 above)
Comment (VirajSalaka) [reply components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/model/mgwdefinition/MgwAPIDefinition.java:137]: code segment is no longer available.

File: components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/model/mgwdefinition/MgwAPIsDefinition.java (hunk 12 above)
Comment (VirajSalaka) [reply components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/model/mgwdefinition/MgwAPIsDefinition.java:43]: code segment is no longer available.

File: components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/utils/GatewayCmdUtils.java (hunk 13 above)
Comment (VirajSalaka) [reply components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/utils/GatewayCmdUtils.java:163]: code segment is no longer available.

File: components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/utils/GatewayCmdUtils.java (hunk 14 above)
Comment (VirajSalaka) [reply components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/utils/GatewayCmdUtils.java:175]: code segment is no longer available.
