### PR TITLE
Fix throttling/scopes related issues in Websockets

### LINKED ISSUE #2672: Scopes support for websocket APIs
### Describe your problem(s)
Subscribing to websocket API topics can be protected based on scopes. To access these topics, the user should have the required set of scopes within the token they provide in the http upgrade request. 

### How will you implement it

---

### LINKED ISSUE #2673: API/Subscription Rate Limiting does not work for websocket APIs
### Description:
API Level throttling and subscription level throttling does not work for websocket APIs. 

### Steps to reproduce:
Create a websocket API. 
Assign a rate limiting policy and invoke.

### Affected Product Version:
Choreo-Connect 1.0.0

### Environment details (with versions):
- OS:
- Client:
- Env (Docker/K8s):

---

### PR DESCRIPTION
**Pull request by VirajSalaka**
### Purpose

$subject.

### Issues

Fixes #2672
Fixes #2673
Fixes Partially #2436 

### Automation tests
 - Unit tests added: No
 - Integration tests added: No

### Tested environments

Not Tested

---
#### Maintainers: Check before merge
- [ ] Assigned 'Type' label
- [ ] Assigned the project
- [ ] Validated respective github issues
- [ ] Assigned milestone to the github issue(s)

### CODE REVIEW

File: adapter/internal/oasparser/envoyconf/routes_with_clusters.go [hunk 1]
```diff
@@ -182,6 +182,19 @@ func CreateRoutesWithClusters(mgwSwagger model.MgwSwagger, upstreamCerts map[str
...
+	// There is a single method, which is a GET.
+	// No topic level endpoints.
+	if mgwSwagger.GetAPIType() == constants.WS {
+		for _, resource := range mgwSwagger.GetResources() {
+			routesP := createRoute(genRouteCreateParams(&mgwSwagger, resource, vHost, apiLevelbasePath, apiLevelClusterNameProd,
+				apiLevelClusterNameSand, nil, nil, organizationID))
+			routes = append(routes, routesP)
+		}
+		return routes, clusters, endpoints
+	}
```
Comment (suksw) [inline adapter/internal/oasparser/envoyconf/routes_with_clusters.go:196]: Should we include the other async API types too? https://github.com/wso2/product-microgateway/blob/151b1d0ed5b8a1bb814b9ac3ef12a6684c507b59/adapter/internal/oasparser/model/api_yaml.go#L243

Comment (suksw) [reply adapter/internal/oasparser/envoyconf/routes_with_clusters.go:196]: Are we sure about not having topic level endpoints?

File: adapter/internal/oasparser/envoyconf/routes_with_clusters_test.go [hunk 2]
```diff
@@ -239,12 +241,26 @@ func TestCreateRoutesWithClustersForEndpointRef(t *testing.T) {
...
+
+	asyncapiFilePath := config.GetMgwHome() + "/../adapter/test-resources/envoycodegen/asyncapi_websocket.yaml"
+	asyncapiByteArr, err := ioutil.ReadFile(asyncapiFilePath)
+	assert.Nil(t, err, "Error while reading file : %v"+asyncapiFilePath)
+	apiJsn, conversionErr := utills.ToJSON(asyncapiByteArr)
+	assert.Nil(t, conversionErr, "YAML to JSON conversion error : %v"+asyncapiFilePath)
+
+	var asyncapi model.AsyncAPI
+	err = json.Unmarshal(apiJsn, &asyncapi)
+	assert.Nil(t, err, "Error occurred while parsing api.yaml")
```
Comment (suksw) [inline adapter/internal/oasparser/envoyconf/routes_with_clusters_test.go:261]:
```suggestion
	assert.Nil(t, err, "Error occurred while parsing asyncapi_websocket.yaml")
```

File: adapter/internal/oasparser/envoyconf/routes_with_clusters_test.go [hunk 3]
```diff
@@ -324,7 +343,19 @@ func testCreateRoutesWithClustersWebsocketWithEnvProps(t *testing.T, apiYamlFile
...
```
Comment (suksw) [inline adapter/internal/oasparser/envoyconf/routes_with_clusters_test.go:356]:
```suggestion
	assert.Nil(t, err, "Error occurred while parsing asyncapi_websocket.yaml")
```

File: adapter/internal/oasparser/envoyconf/routes_with_clusters_test.go [hunk 4]
```diff
@@ -435,15 +466,21 @@ func TestCreateHealthEndpoint(t *testing.T) {
...
```
Comment (suksw) [inline adapter/internal/oasparser/envoyconf/routes_with_clusters_test.go:481]:
```suggestion
	assert.Nil(t, err, "Error occurred while parsing asyncapi_websocket.yaml")
```

File: adapter/internal/oasparser/model/mgw_swagger.go [hunk 5]
```diff
@@ -1244,5 +1244,9 @@ func (swagger *MgwSwagger) PopulateFromAPIYaml(apiYaml APIYaml) error {
 				endpointConfig.APIEndpointSecurity.Sandbox.Type)
 		}
 	}
+
+	if len(data.APIThrottlingPolicy) != 0 {
+		swagger.xWso2ThrottlingTier = data.APIThrottlingPolicy
```
Comment (suksw) [inline adapter/internal/oasparser/model/mgw_swagger.go:1249]: Have added this here https://github.com/wso2/product-microgateway/pull/2667/files#diff-f5f136bd49f2727c3794136db948bbe65b2d521f83119e55ef767fc8939b50c1L1128 . Removed the non-empty check because `swagger.xWso2ThrottlingTier` is a string type.

File: enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/api/WebSocketAPI.java [hunk 6]
```diff
@@ -119,13 +123,35 @@ public String init(Api api) {
...
+            if (securityScheme.getType() != null) {
+                String definitionName = securityScheme.getDefinitionName();
+                SecuritySchemaConfig securitySchemaConfig = new SecuritySchemaConfig();
+                securitySchemaConfig.setDefinitionName(definitionName);
+                securitySchemaConfig.setType(securityScheme.getType());
+                securitySchemaConfig.setName(securityScheme.getName());
+                securitySchemaConfig.setIn(securityScheme.getIn());
+                securitySchemeDefinitions.put(definitionName, securitySchemaConfig);
+            }
+        }
```
Comment (suksw) [inline enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/api/WebSocketAPI.java:146]: We have the security schemes in line 88.

File: enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/api/WebSocketAPI.java [hunk 7]
```diff
@@ -119,13 +123,35 @@ public String init(Api api) {
                     APIProcessUtils.convertProtoEndpointSecurity(
                             api.getEndpointSecurity().getSandBoxSecurityInfo()));
         }
+        for (Resource res : api.getResourcesList()) {
+            for (Operation operation : res.getMethodsList()) {
+                ResourceConfig resConfig = RestAPI.buildResource(operation, res.getPath(), new HashMap<>());
```
Comment (suksw) [inline enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/api/WebSocketAPI.java:128]:
```suggestion
                ResourceConfig resConfig = RestAPI.buildResource(operation, res.getPath(), apiSecurity);
```

**Review by pubudu538 — APPROVED** [review]

File: adapter/internal/oasparser/envoyconf/routes_with_clusters.go (hunk 1 above)
Comment (VirajSalaka) [reply adapter/internal/oasparser/envoyconf/routes_with_clusters.go:196]: https://github.com/wso2/product-microgateway/issues/2677
I created a separate issue here because the webhook APIs should be processed in a different manner compared to websocket APIs. And let's proceed with this for the moment.

File: enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/api/WebSocketAPI.java (hunk 6 above)
Comment (VirajSalaka) [reply enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/api/WebSocketAPI.java]: fixed with https://github.com/wso2/product-microgateway/pull/2667/commits/5b61cc26f7560e106431afd9027b3066aeea76ad

File: adapter/internal/oasparser/model/mgw_swagger.go (hunk 5 above)
Comment (VirajSalaka) [reply adapter/internal/oasparser/model/mgw_swagger.go]: fixed with https://github.com/wso2/product-microgateway/pull/2667/commits/cb8890eee5222009a84259410311d7384bef1664

**Review by suksw — APPROVED** [review]
