### PR TITLE
Handle malformed endpoints

### LINKED ISSUE #2083: Adapter crashes when malformed endpoint is provided
### Description:
Choreo Connect adapter crashes when trying to parse malformed url and does not recover.

### Environment details (with versions):
- OS:
- Client:
- Env (Docker/K8s):

---

### PR DESCRIPTION
**Pull request by ashera96**
### Purpose
Handle malformed endpoints

### Issues
Fixes #2083 

### Automation tests
 - Unit tests added: Yes/No
 - Integration tests added: Yes/No

### Tested environments

Not Tested

---
#### Maintainers: Check before merge
- [x] Assigned 'Type' label
- [x] Assigned the project
- [x] Validated respective github issues
- [x] Assigned milestone to the github issue(s)

### CODE REVIEW

File: adapter/internal/oasparser/model/open_api.go [hunk 1]
```diff
@@ -105,14 +116,18 @@ func setResourcesOpenAPI(openAPI openapi3.Swagger) []Resource {
 						continue
 					}
 					endpoint := getHostandBasepathandPort(serverEntry.URL)
-					resource.productionUrls = append(resource.productionUrls, endpoint)
+					if endpoint != nil {
+						resource.productionUrls = append(resource.productionUrls, *endpoint)
+					} else {
```
Comment (VirajSalaka) [inline adapter/internal/oasparser/model/open_api.go:121]: if the endpoint is not an error right? rather than not a nil

Comment (ashera96) [reply adapter/internal/oasparser/model/open_api.go:121]: Based on the changes made, the function `getHostandBasepathandPort` either returns a pointer to the endpoint or a nil. Hence, it will not return an error.

**Review by pubudu538 — APPROVED** [review]

**Review by VirajSalaka — APPROVED** [review]

File: adapter/internal/oasparser/operator/operator.go [hunk 2]
```diff
@@ -51,7 +51,10 @@ func GetMgwSwagger(apiContent []byte) model.MgwSwagger {
 		if err != nil {
 			logger.LoggerOasparser.Error("Error openAPI unmarsheliing", err)
```
Comment (GDLMadushanka) [inline adapter/internal/oasparser/operator/operator.go:52]: is it not required to return this unmarshal err as well?

Comment (ashera96) [reply adapter/internal/oasparser/operator/operator.go:52]: Just a log would suffice in this particular instance as we just need to know that an unmarshalling error occurred. The problem with returning at this point is, this will stop applying the API as a whole. But since it won't be a breaking error for basic functionalities of the API, we decided to not return. @VirajSalaka correct me if I'm wrong.
