### PR TITLE
Fix minor issues in global throttling

### LINKED ISSUE #1802: Subscription/Application throttling does not work and block the request path.
### Description:
Subscription/Application throttling does not work with newly added policies. Resulting in the following error.

```
enforcer_1  | java.lang.NullPointerException
enforcer_1  | 	at org.wso2.micro.gateway.enforcer.security.KeyValidator.validate(KeyValidator.java:254)
enforcer_1  | 	at org.wso2.micro.gateway.enforcer.security.KeyValidator.validateSubscriptionDetails(KeyValidator.java:202)
enforcer_1  | 	at org.wso2.micro.gateway.enforcer.security.KeyValidator.validateSubscriptionDetails(KeyValidator.java:143)
enforcer_1  | 	at org.wso2.micro.gateway.enforcer.security.KeyValidator.validateSubscription(KeyValidator.java:61)
enforcer_1  | 	at org.wso2.micro.gateway.enforcer.security.jwt.JWTAuthenticator.validateSubscriptionUsingKeyManager(JWTAuthenticator.java:353)
enforcer_1  | 	at org.wso2.micro.gateway.enforcer.security.jwt.JWTAuthenticator.validateSubscriptionUsingKeyManager(JWTAuthenticator.java:341)
enforcer_1  | 	at org.wso2.micro.gateway.enforcer.security.jwt.JWTAuthenticator.authenticate(JWTAuthenticator.java:138)
enforcer_1  | 	at org.wso2.micro.gateway.enforcer.security.AuthFilter.authenticate(AuthFilter.java:119)
enforcer_1  | 	at org.wso2.micro.gateway.enforcer.security.AuthFilter.handleRequest(AuthFilter.java:105)
enforcer_1  | 	at org.wso2.micro.gateway.enforcer.api.API.executeFilterChain(API.java:41)
enforcer_1  | 	at org.wso2.micro.gateway.enforcer.api.RestAPI.process(RestAPI.java:97)
enforcer_1  | 	at org.wso2.micro.gateway.enforcer.server.RequestHandler.process(RequestHandler.java:59)
enforcer_1  | 	at org.wso2.micro.gateway.enforcer.grpc.ExtAuthService.check(ExtAuthService.java:50)
enforcer_1  | 	at io.envoyproxy.envoy.service.auth.v3.AuthorizationGrpc$MethodHandlers.invoke(AuthorizationGrpc.java:245)
enforcer_1  | 	at io.grpc.stub.ServerCalls$UnaryServerCallHandler$UnaryServerCallListener.onHalfClose(ServerCalls.java:180)
enforcer_1  | 	at io.grpc.internal.ServerCallImpl$ServerStreamListenerImpl.halfClosed(ServerCallImpl.java:331)
enforcer_1  | 	at io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$1HalfClosed.runInContext(ServerImpl.java:814)
enforcer_1  | 	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
enforcer_1  | 	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123)
enforcer_1  | 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
enforcer_1  | 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
enforcer_1  | 	at java.base/java.lang.Thread.run(Unknown Source)
```

The cause is the the subscription policy is not updated in the datastore. Hence when the subpolicy extracted from data store it remains null. And afterwards, the microgateway is executing method on the null object. 

### Steps to reproduce:

Create a subscription policy.
Assign to a subscription.
Generate a token
And invoke.

### Affected Product Version:
m10-snapshot

### Environment details (with versions):
- OS: 
- Client:
- Env (Docker/K8s): Docker-with-apim setup with throttling, eventhub and subscription enabled.

---

### LINKED ISSUE #1803: IP Based Throttling not working with X-Forwarded-For header
### Description:
When the X-Forwarded-For header is provided, the IP based throttling should be done based on that header. If not, it should proceed with the source IP address. 

### Steps to reproduce:

Add IP condition-based advanced policy with specific IP.
Provide that IP with X-Forwarded-For header and invoke the gateway.

### Affected Product Version:
m10-snapshot

### Environment details (with versions):
- OS:
- Client:
- Env (Docker/K8s): Docker with apim 

---

### LINKED ISSUE #1844: ADS error during un deploying an API from ctl
### Description:

gRPC marshall error occurs during undeplying of an API using apictl
### Steps to reproduce:
Deploy an API using apictl
Undeploy same API using apictl
Observer the error
### Environment details (with versions):
- OS:
- Client:
- Env (Docker/K8s):

### PR DESCRIPTION
**Pull request by praminda**
### Purpose

- Push dynamic policy updates to enforcer
- Fix an issue in undeploying API
- Prioritize x-forwarded-for header as clientIp
### Issues

Fixes #1802
Fixes #1803 
Fixes #1844

### Automation tests
 - Unit tests added: No
 - Integration tests added: No

### Tested environments

Mac

---
#### Maintainers: Check before merge
- [x] Assigned 'Type' label
- [x] Assigned the project
- [x] Validated respective github issues
- [x] Assigned milestone to the github issue(s)

### CODE REVIEW

File: adapter/internal/discovery/xds/server.go [hunk 1]
```diff
@@ -357,7 +357,10 @@ func GenerateEnvoyResoucesForLabel(label string) ([]types.Resource, []types.Reso
 			clusterArray = append(clusterArray, openAPIClustersMap[apiKey]...)
 			routeArray = append(routeArray, openAPIRoutesMap[apiKey]...)
 			endpointArray = append(endpointArray, openAPIEndpointsMap[apiKey]...)
-			apis = append(apis, openAPIEnforcerApisMap[apiKey])
+			enfocerAPI, err := openAPIEnforcerApisMap[apiKey]
+			if err {
```
Comment (Rajith90) [inline adapter/internal/discovery/xds/server.go:361]: Do we add the API in case of error

File: adapter/internal/messaging/notification_listener.go [hunk 2]
```diff
@@ -88,12 +88,11 @@ func handleNotification(deliveries <-chan amqp.Delivery, done chan error) {
 			handleApplicationEvents(decodedByte, eventType)
 		} else if strings.Contains(eventType, subscriptionEventType) {
 			handleSubscriptionEvents(decodedByte, eventType)
+		} else if strings.Contains(eventType, scopeEvenType) {
```
Comment (Rajith90) [inline adapter/internal/messaging/notification_listener.go:91]: I think we can remove this, since there is no such event

File: adapter/internal/discovery/xds/server.go (hunk 1 above)
Comment (VirajSalaka) [reply adapter/internal/discovery/xds/server.go:361]: variable is not an error rather `ok` or `found`

**Review by Rajith90 — APPROVED** [review]
