### PR TITLE
Fix deployment status retries

### LINKED ISSUE #2181: Issue in retries of the deployment message
### Description:

Error is always not nil when retrying the deployment message to internal/data/v1/apis/deployed-revisions

### Environment details (with versions):
- OS:
- Client:
- Env (Docker/K8s):

---

### PR DESCRIPTION
**Pull request by AmaliMatharaarachchi**
### Issues

Fixes #2181
Related to changes introduced in https://github.com/wso2/carbon-apimgt/pull/10698

### Automation tests
 - Unit tests added: No
 - Integration tests added: No

### Tested environments

Not Tested

---
#### Maintainers: Check before merge
- [x] Assigned 'Type' label
- [x] Assigned the project
- [x] Validated respective github issues
- [x] Assigned milestone to the github issue(s)

### CODE REVIEW

File: adapter/internal/notifier/deployment_notifier.go [hunk 1]
```diff
@@ -49,26 +50,34 @@ func SendRevisionUpdate(deployedRevisionList []*DeployedAPIRevision) {
...
 	retries := 0
 	for retries < 3 {
 		retries++
+
+		req, _ := http.NewRequest("PATCH", revisionEP, bytes.NewBuffer(jsonValue))
+		req.Header.Set("Authorization", basicAuth)
+		req.Header.Set("Content-Type", "application/json")
 		resp, err := tlsutils.InvokeControlPlane(req, cpConfigs.SkipSSLVerification)
+
+		success := true
```
Comment (Rajith90) [inline adapter/internal/notifier/deployment_notifier.go:69]: Can't we initially set success as false, and then set to true inside the loop

File: adapter/internal/notifier/deployment_notifier.go [hunk 2]
```diff
@@ -49,26 +50,34 @@ func SendRevisionUpdate(deployedRevisionList []*DeployedAPIRevision) {
...
-	req.Header.Set("Content-Type", "application/json")
+
+	logger.LoggerNotifier.Debugf("Revision deployed message sending to Control plane: %v", string(jsonValue))
 
 	// Adding 3 retries for revision update sending
 	retries := 0
 	for retries < 3 {
 		retries++
+
+		req, _ := http.NewRequest("PATCH", revisionEP, bytes.NewBuffer(jsonValue))
```
Comment (Rajith90) [inline adapter/internal/notifier/deployment_notifier.go:64]: Is the REST API resource is type patch to update the revision

Comment (AmaliMatharaarachchi) [reply adapter/internal/notifier/deployment_notifier.go:64]: As a suggestion from @malinthaprasan, we changed the rest api type to patch.

File: adapter/internal/notifier/deployment_notifier.go (hunk 1 above)
Comment (AmaliMatharaarachchi) [reply adapter/internal/notifier/deployment_notifier.go:69]: We can. I suppose it would add an additional condition checks like follows. 
```if err != nil && resp != nil && resp.StatusCode == http.StatusOK {success=true}```
Since we have already done the negation of the above condition for logging purposes, I guess keeping it as it is would be convenient.

File: adapter/internal/notifier/deployment_notifier.go (hunk 2 above)
Comment (AmaliMatharaarachchi) [reply adapter/internal/notifier/deployment_notifier.go:64]: https://github.com/wso2/carbon-apimgt/pull/10698#discussion_r678804383

**Review by Rajith90 — APPROVED** [review]

**Comment by choreo-cicd** [comment]
[succeeded] dev-deployment : 20210730.1

**Comment by choreo-cicd** [comment]
[succeeded] prod-deployment : 20210804.1
