### PR TITLE
Bug fixes and improvements

### LINKED ISSUE #1832: Subscription unblocking does not works
### Description:
Blocking and unblocking the subscription would still not allow the API to be accessed. 

### Steps to reproduce:
1. Block a subscription from publisher portal(click block production only)
2.  Then invoke , we will get below message.
```{"error_message":"The requested API is temporarily blocked","code":"900907","error_description":"User is NOT authorized to access the Resource. API Subscription validation failed."}```
3.  Then unblock ad invoke the API. It still does not allow and gives a different error message
```{"error_message":"Message blocked","code":"900805","error_description":"You have been blocked from accessing the resource"}```

### Environment details (with versions):
- OS:
- Client:
- Env (Docker/K8s):

---

### LINKED ISSUE #1848: Application Level Throttling does not work with self contained access tokens
### Description:
When self contained access token is used, application throttling does not work.

### Steps to reproduce:
Get a self contained access token with application throttle tier is set to 10PerMin.
Start docker-with-apim setup 
Create a matching API within api manager
Invoke the API such that the throttle limit is exceeded. 

### Affected Product Version:
m10-snapshot

### Environment details (with versions):
- OS:
- Client:
- Env (Docker/K8s): docker-with-apim

---

### PR DESCRIPTION
**Pull request by praminda**
### Purpose

- Fix subscription unblocking
- Populate authcontext for self jwt
- Make endpoint security work for self jwt 
### Issues

Fixes #1832
Fixes #1848

### Automation tests
 - Unit tests added: No
 - Integration tests added: No

### Tested environments

Mac

---
#### Maintainers: Check before merge
- [x] Assigned 'Type' label
- [x] Assigned the project
- [x] Validated respective github issues
- [x] Assigned milestone to the github issue(s)

### CODE REVIEW

File: adapter/internal/messaging/throttle_data_listener.go [hunk 1]
```diff
@@ -51,6 +51,11 @@ func handleThrottleData(deliveries <-chan amqp.Delivery, done chan error) {
 
 		payload := data.Event.PayloadData
 		if payload.BlockingCondition != "" {
+			// control plane sends a blocking throttle data event for subscription blocking.
+			// this is not required and causes issues in evaluating subscription blocking.
+			if payload.BlockingCondition == "SUBSCRIPTION" {
```
Comment (praminda) [inline adapter/internal/messaging/throttle_data_listener.go:56]: This is not going to be used anywhere else, hence no need of using a separate const

**Review by Rajith90 — APPROVED** [review]
